/**
 * Comprehensive Medication Database
 *
 * Generated from top 300 prescribed medications in the US (2023)
 * Source: ClinCalc DrugStats Database
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generateMedicationDatabase.ts
 */

export interface MedicationEntry {
  correct: string;
  variations: string[];
  drugClass?: string;
  brandNames?: string[];
}

export const MEDICATION_DATABASE: Record<string, MedicationEntry> = {
  'acetaminophen': {
    correct: 'Acetaminophen',
    variations: ['acetaminofen', 'asetaminophen', 'caetaminophen', 'aectaminophen', 'acteaminophen', 'aceatminophen', 'acetmainophen', 'acetaimnophen', 'tylenol'],
    drugClass: 'Analgesic',
    brandNames: ['Tylenol'],
  },
  'acyclovir': {
    correct: 'Acyclovir',
    variations: ['acycllovvir', 'cayclovir', 'aycclovir', 'accylovir', 'acylcovir', 'acycolvir', 'acyclvoir', 'acycloivr', 'zovirax'],
    brandNames: ['Zovirax'],
  },
  'adalimumab': {
    correct: 'Adalimumab',
    variations: ['daalimumab', 'aadlimumab', 'adlaimumab', 'adailmumab', 'adalmiumab', 'adaliummab', 'adalimmuab', 'adalimuamb', 'humira'],
    brandNames: ['Humira'],
  },
  'albuterol': {
    correct: 'Albuterol',
    variations: ['labuterol', 'abluterol', 'alubterol', 'albtuerol', 'albuetrol', 'albutreol', 'albuteorl', 'albuterlo', 'proventil', 'ventolin', 'proair'],
    drugClass: 'Beta-2 Agonist',
    brandNames: ['Proventil', 'Ventolin', 'ProAir'],
  },
  'alendronate': {
    correct: 'Alendronate',
    variations: ['laendronate', 'aelndronate', 'alnedronate', 'alednronate', 'alenrdonate', 'alendornate', 'alendrnoate', 'alendroante', 'fosamax'],
    brandNames: ['Fosamax'],
  },
  'allopurinol': {
    correct: 'Allopurinol',
    variations: ['alopurinol', 'lalopurinol', 'alolpurinol', 'allpourinol', 'allouprinol', 'allopruinol', 'allopuirnol', 'allopurniol', 'zyloprim'],
    drugClass: 'Xanthine Oxidase Inhibitor',
    brandNames: ['Zyloprim'],
  },
  'alprazolam': {
    correct: 'Alprazolam',
    variations: ['alprasolam', 'alpraxolam', 'laprazolam', 'aplrazolam', 'alrpazolam', 'alparzolam', 'alprzaolam', 'alpraozlam', 'xanax'],
    drugClass: 'Benzodiazepine',
    brandNames: ['Xanax'],
  },
  'amiodarone': {
    correct: 'Amiodarone',
    variations: ['maiodarone', 'aimodarone', 'amoidarone', 'amidoarone', 'amioadrone', 'amiodraone', 'amiodaorne', 'amiodarnoe', 'cordarone', 'pacerone'],
    brandNames: ['Cordarone', 'Pacerone'],
  },
  'amitriptyline': {
    correct: 'Amitriptyline',
    variations: ['maitriptyline', 'aimtriptyline', 'amtiriptyline', 'amirtiptyline', 'amitirptyline', 'amitrpityline', 'amitritpyline', 'amitripytline', 'elavil'],
    brandNames: ['Elavil'],
  },
  'amlodipine': {
    correct: 'Amlodipine',
    variations: ['malodipine', 'almodipine', 'amoldipine', 'amldoipine', 'amloidpine', 'amlodpiine', 'amlodiipne', 'amlodipnie', 'norvasc'],
    drugClass: 'Calcium Channel Blocker',
    brandNames: ['Norvasc'],
  },
  'amoxicillin': {
    correct: 'Amoxicillin',
    variations: ['amoxisillin', 'amozicillin', 'amoxicilin', 'maoxicillin', 'aomxicillin', 'amxoicillin', 'amoixcillin', 'amoxciillin', 'amoxil', 'moxatag'],
    drugClass: 'Penicillin Antibiotic',
    brandNames: ['Amoxil', 'Moxatag'],
  },
  'anastrozole': {
    correct: 'Anastrozole',
    variations: ['anastrosole', 'anastroxole', 'naastrozole', 'aanstrozole', 'ansatrozole', 'anatsrozole', 'anasrtozole', 'anastorzole', 'arimidex'],
    brandNames: ['Arimidex'],
  },
  'apixaban': {
    correct: 'Apixaban',
    variations: ['apizaban', 'paixaban', 'aipxaban', 'apxiaban', 'apiaxban', 'apixbaan', 'apixaabn', 'apixabna', 'eliquis'],
    drugClass: 'Anticoagulant',
    brandNames: ['Eliquis'],
  },
  'aripiprazole': {
    correct: 'Aripiprazole',
    variations: ['aripiprasole', 'aripipraxole', 'raipiprazole', 'airpiprazole', 'arpiiprazole', 'ariipprazole', 'arippirazole', 'aripirpazole', 'abilify'],
    drugClass: 'Atypical Antipsychotic',
    brandNames: ['Abilify'],
  },
  'ascorbicacid': {
    correct: 'Ascorbic Acid',
    variations: ['ascorbic asid', 'sacorbic acid', 'acsorbic acid', 'asocrbic acid', 'ascrobic acid', 'ascobric acid', 'ascoribc acid', 'ascorbci acid'],
  },
  'aspirin': {
    correct: 'Aspirin',
    variations: ['asppirrin', 'sapirin', 'apsirin', 'asiprin', 'aspriin', 'aspiirn', 'aspirni', 'bayer', 'ecotrin'],
    drugClass: 'Antiplatelet',
    brandNames: ['Bayer', 'Ecotrin'],
  },
  'atenolol': {
    correct: 'Atenolol',
    variations: ['taenolol', 'aetnolol', 'atneolol', 'ateonlol', 'atenlool', 'atenooll', 'atenollo', 'atenalol', 'tenormin'],
    drugClass: 'Beta-Blocker',
    brandNames: ['Tenormin'],
  },
  'atomoxetine': {
    correct: 'Atomoxetine',
    variations: ['atomozetine', 'taomoxetine', 'aotmoxetine', 'atmooxetine', 'atoomxetine', 'atomxoetine', 'atomoextine', 'atomoxteine', 'strattera'],
    brandNames: ['Strattera'],
  },
  'atorvastatin': {
    correct: 'Atorvastatin',
    variations: ['taorvastatin', 'aotrvastatin', 'atrovastatin', 'atovrastatin', 'atoravstatin', 'atorvsatatin', 'atorvatsatin', 'atorvasattin', 'lipitor'],
    drugClass: 'Statin',
    brandNames: ['Lipitor'],
  },
  'azelastine': {
    correct: 'Azelastine',
    variations: ['aselastine', 'axelastine', 'zaelastine', 'aezlastine', 'azleastine', 'azealstine', 'azelsatine', 'azelatsine', 'astelin', 'astepro'],
    drugClass: 'Antihistamine',
    brandNames: ['Astelin', 'Astepro'],
  },
  'azithromycin': {
    correct: 'Azithromycin',
    variations: ['azithromysin', 'asithromycin', 'axithromycin', 'zaithromycin', 'aizthromycin', 'aztihromycin', 'azihtromycin', 'azitrhomycin', 'zithromax', 'z-pak', 'zpak'],
    drugClass: 'Macrolide Antibiotic',
    brandNames: ['Zithromax', 'Z-Pak'],
  },
  'baclofen': {
    correct: 'Baclofen',
    variations: ['baclophen', 'abclofen', 'bcalofen', 'balcofen', 'bacolfen', 'baclfoen', 'bacloefn', 'baclofne', 'lioresal'],
    drugClass: 'Muscle Relaxant',
    brandNames: ['Lioresal'],
  },
  'benazepril': {
    correct: 'Benazepril',
    variations: ['benasepril', 'benaxepril', 'ebnazepril', 'bneazepril', 'beanzepril', 'benzaepril', 'benaezpril', 'benazperil', 'lotensin'],
    drugClass: 'ACE Inhibitor',
    brandNames: ['Lotensin'],
  },
  'benzonatate': {
    correct: 'Benzonatate',
    variations: ['bensonatate', 'benxonatate', 'ebnzonatate', 'bnezonatate', 'beznonatate', 'benoznatate', 'benznoatate', 'benzoantate', 'tessalon'],
    brandNames: ['Tessalon'],
  },
  'betamethasone': {
    correct: 'Betamethasone',
    variations: ['ebtamethasone', 'bteamethasone', 'beatmethasone', 'betmaethasone', 'betaemthasone', 'betamtehasone', 'betamehtasone', 'betametahsone', 'celestone'],
    drugClass: 'Corticosteroid',
    brandNames: ['Celestone'],
  },
  'bimatoprost': {
    correct: 'Bimatoprost',
    variations: ['ibmatoprost', 'bmiatoprost', 'biamtoprost', 'bimtaoprost', 'bimaotprost', 'bimatporost', 'bimatorpost', 'bimatoporst', 'lumigan'],
    brandNames: ['Lumigan'],
  },
  'bisacodyl': {
    correct: 'Bisacodyl',
    variations: ['ibsacodyl', 'bsiacodyl', 'biascodyl', 'biscaodyl', 'bisaocdyl', 'bisacdoyl', 'bisacoydl', 'bisacodly'],
  },
  'bisoprolol': {
    correct: 'Bisoprolol',
    variations: ['ibsoprolol', 'bsioprolol', 'biosprolol', 'bisporolol', 'bisorpolol', 'bisoporlol', 'bisoprlool', 'bisoprooll', 'zebeta'],
    drugClass: 'Beta-Blocker',
    brandNames: ['Zebeta'],
  },
  'brimonidine': {
    correct: 'Brimonidine',
    variations: ['rbimonidine', 'birmonidine', 'brmionidine', 'briomnidine', 'brimnoidine', 'brimoindine', 'brimondiine', 'brimoniidne', 'alphagan'],
    brandNames: ['Alphagan'],
  },
  'budesonide': {
    correct: 'Budesonide',
    variations: ['ubdesonide', 'bduesonide', 'buedsonide', 'budseonide', 'budeosnide', 'budesnoide', 'budesoinde', 'budesondie', 'pulmicort', 'entocort'],
    drugClass: 'Corticosteroid',
    brandNames: ['Pulmicort', 'Entocort'],
  },
  'bumetanide': {
    correct: 'Bumetanide',
    variations: ['ubmetanide', 'bmuetanide', 'buemtanide', 'bumteanide', 'bumeatnide', 'bumetnaide', 'bumetainde', 'bumetandie', 'bumex'],
    drugClass: 'Loop Diuretic',
    brandNames: ['Bumex'],
  },
  'bupropion': {
    correct: 'Bupropion',
    variations: ['ubpropion', 'bpuropion', 'burpopion', 'buporpion', 'buprpoion', 'buproipon', 'bupropoin', 'bupropino', 'wellbutrin', 'zyban'],
    brandNames: ['Wellbutrin', 'Zyban'],
  },
  'buspirone': {
    correct: 'Buspirone',
    variations: ['ubspirone', 'bsupirone', 'bupsirone', 'busiprone', 'busprione', 'buspiorne', 'buspirnoe', 'buspiroen', 'buspar'],
    brandNames: ['Buspar'],
  },
  'calcitriol': {
    correct: 'Calcitriol',
    variations: ['calsitriol', 'aclcitriol', 'clacitriol', 'caclitriol', 'calictriol', 'calctiriol', 'calcirtiol', 'calcitirol'],
  },
  'calcium': {
    correct: 'Calcium',
    variations: ['calsium', 'ccalccium', 'aclcium', 'clacium', 'caclium', 'calicum', 'calcuim', 'calcimu'],
  },
  'carbamazepine': {
    correct: 'Carbamazepine',
    variations: ['carbamasepine', 'carbamaxepine', 'acrbamazepine', 'crabamazepine', 'cabramazepine', 'carabmazepine', 'carbmaazepine', 'carbaamzepine', 'tegretol', 'carbatrol'],
    drugClass: 'Anticonvulsant',
    brandNames: ['Tegretol', 'Carbatrol'],
  },
  'carvedilol': {
    correct: 'Carvedilol',
    variations: ['acrvedilol', 'cravedilol', 'cavredilol', 'carevdilol', 'carvdeilol', 'carveidlol', 'carvedliol', 'carvedioll', 'coreg'],
    drugClass: 'Beta-Blocker',
    brandNames: ['Coreg'],
  },
  'cefdinir': {
    correct: 'Cefdinir',
    variations: ['cephdinir', 'sefdinir', 'ecfdinir', 'cfedinir', 'cedfinir', 'cefidnir', 'cefdniir', 'cefdiinr', 'omnicef'],
    drugClass: 'Cephalosporin',
    brandNames: ['Omnicef'],
  },
  'cefuroxime': {
    correct: 'Cefuroxime',
    variations: ['cephuroxime', 'sefuroxime', 'cefurozime', 'ecfuroxime', 'cfeuroxime', 'ceufroxime', 'cefruoxime', 'cefuorxime', 'ceftin'],
    drugClass: 'Cephalosporin',
    brandNames: ['Ceftin'],
  },
  'celecoxib': {
    correct: 'Celecoxib',
    variations: ['selecoxib', 'celecozib', 'eclecoxib', 'cleecoxib', 'ceelcoxib', 'celceoxib', 'celeocxib', 'celecxoib', 'celebrex'],
    drugClass: 'COX-2 Inhibitor',
    brandNames: ['Celebrex'],
  },
  'cephalexin': {
    correct: 'Cephalexin',
    variations: ['cefalexin', 'sephalexin', 'cephalezin', 'ecphalexin', 'cpehalexin', 'cehpalexin', 'cepahlexin', 'cephlaexin', 'keflex'],
    drugClass: 'Cephalosporin',
    brandNames: ['Keflex'],
  },
  'cetirizine': {
    correct: 'Cetirizine',
    variations: ['setirizine', 'cetirisine', 'cetirixine', 'ectirizine', 'cteirizine', 'ceitrizine', 'cetriizine', 'cetiirzine', 'zyrtec'],
    drugClass: 'Antihistamine',
    brandNames: ['Zyrtec'],
  },
  'chlorhexidine': {
    correct: 'Chlorhexidine',
    variations: ['chlorhezidine', 'hclorhexidine', 'clhorhexidine', 'cholrhexidine', 'chlrohexidine', 'chlohrexidine', 'chlorehxidine', 'chlorhxeidine'],
  },
  'chlorthalidone': {
    correct: 'Chlorthalidone',
    variations: ['hclorthalidone', 'clhorthalidone', 'cholrthalidone', 'chlrothalidone', 'chlotrhalidone', 'chlorhtalidone', 'chlortahlidone', 'chlorthlaidone', 'thalitone'],
    drugClass: 'Thiazide-Like Diuretic',
    brandNames: ['Thalitone'],
  },
  'cholecalciferol': {
    correct: 'Cholecalciferol',
    variations: ['cholecalcipherol', 'cholecalsiferol', 'hcolecalciferol', 'cohlecalciferol', 'chloecalciferol', 'choelcalciferol', 'cholcealciferol', 'choleaclciferol'],
  },
  'ciclopirox': {
    correct: 'Ciclopirox',
    variations: ['siclopirox', 'ciclopiroz', 'icclopirox', 'ccilopirox', 'cilcopirox', 'cicolpirox', 'ciclpoirox', 'cicloiprox'],
  },
  'ciprofloxacin': {
    correct: 'Ciprofloxacin',
    variations: ['ciprophloxacin', 'siprofloxasin', 'ciproflozacin', 'icprofloxacin', 'cpirofloxacin', 'cirpofloxacin', 'ciporfloxacin', 'ciprfoloxacin', 'cipro'],
    drugClass: 'Fluoroquinolone',
    brandNames: ['Cipro'],
  },
  'citalopram': {
    correct: 'Citalopram',
    variations: ['sitalopram', 'ictalopram', 'ctialopram', 'ciatlopram', 'citlaopram', 'citaolpram', 'citalporam', 'citalorpam', 'celexa'],
    drugClass: 'SSRI',
    brandNames: ['Celexa'],
  },
  'clindamycin': {
    correct: 'Clindamycin',
    variations: ['clindamysin', 'lcindamycin', 'cilndamycin', 'clnidamycin', 'clidnamycin', 'clinadmycin', 'clindmaycin', 'clindaymcin', 'cleocin'],
    drugClass: 'Lincosamide Antibiotic',
    brandNames: ['Cleocin'],
  },
  'clobetasol': {
    correct: 'Clobetasol',
    variations: ['lcobetasol', 'colbetasol', 'clboetasol', 'cloebtasol', 'clobteasol', 'clobeatsol', 'clobetsaol', 'clobetaosl'],
  },
  'clonazepam': {
    correct: 'Clonazepam',
    variations: ['clonasepam', 'clonaxepam', 'lconazepam', 'colnazepam', 'clnoazepam', 'cloanzepam', 'clonzaepam', 'clonaezpam', 'klonopin'],
    drugClass: 'Benzodiazepine',
    brandNames: ['Klonopin'],
  },
  'clonidine': {
    correct: 'Clonidine',
    variations: ['lconidine', 'colnidine', 'clnoidine', 'cloindine', 'clondiine', 'cloniidne', 'clonidnie', 'clonidien', 'catapres'],
    brandNames: ['Catapres'],
  },
  'clopidogrel': {
    correct: 'Clopidogrel',
    variations: ['lcopidogrel', 'colpidogrel', 'clpoidogrel', 'cloipdogrel', 'clopdiogrel', 'clopiodgrel', 'clopidgorel', 'clopidorgel', 'plavix'],
    drugClass: 'Antiplatelet',
    brandNames: ['Plavix'],
  },
  'clotrimazole': {
    correct: 'Clotrimazole',
    variations: ['clotrimasole', 'clotrimaxole', 'lcotrimazole', 'coltrimazole', 'cltorimazole', 'clortimazole', 'clotirmazole', 'clotrmiazole', 'lotrimin'],
    brandNames: ['Lotrimin'],
  },
  'colchicine': {
    correct: 'Colchicine',
    variations: ['colchisine', 'oclchicine', 'clochicine', 'coclhicine', 'colhcicine', 'colcihcine', 'colchciine', 'colchiicne', 'colcrys'],
    brandNames: ['Colcrys'],
  },
  'cyanocobalamin': {
    correct: 'Cyanocobalamin',
    variations: ['ycanocobalamin', 'caynocobalamin', 'cynaocobalamin', 'cyaoncobalamin', 'cyancoobalamin', 'cyanoocbalamin', 'cyanocboalamin', 'cyanocoablamin'],
  },
  'cyclobenzaprine': {
    correct: 'Cyclobenzaprine',
    variations: ['cyclobensaprine', 'cyclobenxaprine', 'ycclobenzaprine', 'ccylobenzaprine', 'cylcobenzaprine', 'cycolbenzaprine', 'cyclboenzaprine', 'cycloebnzaprine', 'flexeril', 'amrix'],
    drugClass: 'Muscle Relaxant',
    brandNames: ['Flexeril', 'Amrix'],
  },
  'cyclosporine': {
    correct: 'Cyclosporine',
    variations: ['ycclosporine', 'ccylosporine', 'cylcosporine', 'cycolsporine', 'cyclsoporine', 'cyclopsorine', 'cyclosoprine', 'cyclosproine', 'neoral', 'sandimmune'],
    brandNames: ['Neoral', 'Sandimmune'],
  },
  'cyproheptadine': {
    correct: 'Cyproheptadine',
    variations: ['ycproheptadine', 'cpyroheptadine', 'cyrpoheptadine', 'cyporheptadine', 'cyprhoeptadine', 'cyproehptadine', 'cyprohpetadine', 'cyprohetpadine'],
  },
  'dapagliflozin': {
    correct: 'Dapagliflozin',
    variations: ['dapagliphlozin', 'dapagliflosin', 'dapaglifloxin', 'adpagliflozin', 'dpaagliflozin', 'daapgliflozin', 'dapgaliflozin', 'dapalgiflozin', 'farxiga'],
    drugClass: 'SGLT2 Inhibitor',
    brandNames: ['Farxiga'],
  },
  'desvenlafaxine': {
    correct: 'Desvenlafaxine',
    variations: ['desvenlaphaxine', 'desvenlafazine', 'edsvenlafaxine', 'dsevenlafaxine', 'devsenlafaxine', 'desevnlafaxine', 'desvnelafaxine', 'desvelnafaxine', 'pristiq'],
    drugClass: 'SNRI',
    brandNames: ['Pristiq'],
  },
  'dexamethasone': {
    correct: 'Dexamethasone',
    variations: ['dezamethasone', 'edxamethasone', 'dxeamethasone', 'deaxmethasone', 'dexmaethasone', 'dexaemthasone', 'dexamtehasone', 'dexamehtasone', 'decadron'],
    drugClass: 'Corticosteroid',
    brandNames: ['Decadron'],
  },
  'dexmethylphenidate': {
    correct: 'Dexmethylphenidate',
    variations: ['dexmethylfenidate', 'dezmethylphenidate', 'edxmethylphenidate', 'dxemethylphenidate', 'demxethylphenidate', 'dexemthylphenidate', 'dexmtehylphenidate', 'dexmehtylphenidate'],
    drugClass: 'Stimulant',
  },
  'dextroamphetamine': {
    correct: 'Dextroamphetamine',
    variations: ['dextroamfetamine', 'deztroamphetamine', 'edxtroamphetamine', 'dxetroamphetamine', 'detxroamphetamine', 'dexrtoamphetamine', 'dextoramphetamine', 'dextraomphetamine'],
    drugClass: 'Stimulant',
  },
  'diazepam': {
    correct: 'Diazepam',
    variations: ['diasepam', 'diaxepam', 'idazepam', 'daizepam', 'dizaepam', 'diaezpam', 'diazpeam', 'diazeapm', 'valium'],
    drugClass: 'Benzodiazepine',
    brandNames: ['Valium'],
  },
  'diclofenac': {
    correct: 'Diclofenac',
    variations: ['diclophenac', 'idclofenac', 'dcilofenac', 'dilcofenac', 'dicolfenac', 'diclfoenac', 'dicloefnac', 'diclofneac', 'voltaren'],
    drugClass: 'NSAID',
    brandNames: ['Voltaren'],
  },
  'dicyclomine': {
    correct: 'Dicyclomine',
    variations: ['idcyclomine', 'dciyclomine', 'diycclomine', 'diccylomine', 'dicylcomine', 'dicycolmine', 'dicyclmoine', 'dicycloimne', 'bentyl'],
    brandNames: ['Bentyl'],
  },
  'diltiazem': {
    correct: 'Diltiazem',
    variations: ['diltiasem', 'diltiaxem', 'idltiazem', 'dlitiazem', 'ditliazem', 'dilitazem', 'diltaizem', 'diltizaem', 'cardizem', 'tiazac'],
    drugClass: 'Calcium Channel Blocker',
    brandNames: ['Cardizem', 'Tiazac'],
  },
  'diphenhydramine': {
    correct: 'Diphenhydramine',
    variations: ['difenhydramine', 'idphenhydramine', 'dpihenhydramine', 'dihpenhydramine', 'dipehnhydramine', 'diphnehydramine', 'diphehnydramine', 'diphenyhdramine', 'benadryl'],
    drugClass: 'Antihistamine',
    brandNames: ['Benadryl'],
  },
  'docusate': {
    correct: 'Docusate',
    variations: ['odcusate', 'dcousate', 'doucsate', 'docsuate', 'docuaste', 'docustae', 'docusaet', 'colace'],
    brandNames: ['Colace'],
  },
  'donepezil': {
    correct: 'Donepezil',
    variations: ['donepesil', 'donepexil', 'odnepezil', 'dnoepezil', 'doenpezil', 'donpeezil', 'doneepzil', 'donepzeil', 'aricept'],
    drugClass: 'Cholinesterase Inhibitor',
    brandNames: ['Aricept'],
  },
  'dorzolamide': {
    correct: 'Dorzolamide',
    variations: ['dorsolamide', 'dorxolamide', 'odrzolamide', 'drozolamide', 'dozrolamide', 'dorozlamide', 'dorzloamide', 'dorzoalmide'],
  },
  'doxazosin': {
    correct: 'Doxazosin',
    variations: ['doxazocin', 'doxasosin', 'dozazosin', 'doxaxosin', 'odxazosin', 'dxoazosin', 'doaxzosin', 'doxzaosin', 'cardura'],
    drugClass: 'Alpha Blocker',
    brandNames: ['Cardura'],
  },
  'doxepin': {
    correct: 'Doxepin',
    variations: ['dozepin', 'odxepin', 'dxoepin', 'doexpin', 'doxpein', 'doxeipn', 'doxepni', 'sinequan', 'silenor'],
    brandNames: ['Sinequan', 'Silenor'],
  },
  'doxycycline': {
    correct: 'Doxycycline',
    variations: ['dozycycline', 'odxycycline', 'dxoycycline', 'doyxcycline', 'doxcyycline', 'doxyyccline', 'doxyccyline', 'doxycylcine'],
    drugClass: 'Tetracycline',
  },
  'dulaglutide': {
    correct: 'Dulaglutide',
    variations: ['udlaglutide', 'dluaglutide', 'dualglutide', 'dulgalutide', 'dulalgutide', 'dulagultide', 'dulagltuide', 'dulagluitde', 'trulicity'],
    drugClass: 'GLP-1 Agonist',
    brandNames: ['Trulicity'],
  },
  'duloxetine': {
    correct: 'Duloxetine',
    variations: ['dulozetine', 'udloxetine', 'dluoxetine', 'duolxetine', 'dulxoetine', 'duloextine', 'duloxteine', 'duloxeitne', 'cymbalta'],
    drugClass: 'SNRI',
    brandNames: ['Cymbalta'],
  },
  'dutasteride': {
    correct: 'Dutasteride',
    variations: ['udtasteride', 'dtuasteride', 'duatsteride', 'dutsateride', 'dutatseride', 'dutasetride', 'dutastreide', 'dutasteirde', 'avodart'],
    drugClass: '5-Alpha Reductase Inhibitor',
    brandNames: ['Avodart'],
  },
  'empagliflozin': {
    correct: 'Empagliflozin',
    variations: ['empagliphlozin', 'empagliflosin', 'empaglifloxin', 'mepagliflozin', 'epmagliflozin', 'emapgliflozin', 'empgaliflozin', 'empalgiflozin', 'jardiance'],
    drugClass: 'SGLT2 Inhibitor',
    brandNames: ['Jardiance'],
  },
  'enalapril': {
    correct: 'Enalapril',
    variations: ['nealapril', 'eanlapril', 'enlaapril', 'enaalpril', 'enalparil', 'enalarpil', 'enalapirl', 'enalaprli', 'vasotec'],
    drugClass: 'ACE Inhibitor',
    brandNames: ['Vasotec'],
  },
  'epinephrine': {
    correct: 'Epinephrine',
    variations: ['epinefrine', 'peinephrine', 'eipnephrine', 'epniephrine', 'epienphrine', 'epinpehrine', 'epinehprine', 'epineprhine'],
  },
  'ergocalciferol': {
    correct: 'Ergocalciferol',
    variations: ['ergocalcipherol', 'ergocalsiferol', 'regocalciferol', 'egrocalciferol', 'erogcalciferol', 'ergcoalciferol', 'ergoaclciferol', 'ergoclaciferol'],
  },
  'erythromycin': {
    correct: 'Erythromycin',
    variations: ['erythromysin', 'erythrromyccin', 'reythromycin', 'eyrthromycin', 'ertyhromycin', 'eryhtromycin', 'erytrhomycin', 'erythormycin', 'e-mycin', 'emycin', 'ery-tab', 'erytab'],
    drugClass: 'Macrolide Antibiotic',
    brandNames: ['E-Mycin', 'Ery-Tab'],
  },
  'escitalopram': {
    correct: 'Escitalopram',
    variations: ['essitalopram', 'secitalopram', 'ecsitalopram', 'esictalopram', 'esctialopram', 'esciatlopram', 'escitlaopram', 'escitaolpram', 'lexapro'],
    drugClass: 'SSRI',
    brandNames: ['Lexapro'],
  },
  'esomeprazole': {
    correct: 'Esomeprazole',
    variations: ['esomeprasole', 'esomepraxole', 'seomeprazole', 'eosmeprazole', 'esmoeprazole', 'esoemprazole', 'esomperazole', 'esomerpazole', 'nexium'],
    drugClass: 'Proton Pump Inhibitor',
    brandNames: ['Nexium'],
  },
  'estradiol': {
    correct: 'Estradiol',
    variations: ['estrraddiol', 'setradiol', 'etsradiol', 'esrtadiol', 'estardiol', 'estrdaiol', 'estraidol', 'estradoil', 'estrace', 'vivelle'],
    brandNames: ['Estrace', 'Vivelle'],
  },
  'etodolac': {
    correct: 'Etodolac',
    variations: ['teodolac', 'eotdolac', 'etdoolac', 'etoodlac', 'etodloac', 'etodoalc', 'etodolca'],
  },
  'evolocumab': {
    correct: 'Evolocumab',
    variations: ['veolocumab', 'eovlocumab', 'evloocumab', 'evoolcumab', 'evolcoumab', 'evoloucmab', 'evolocmuab', 'evolocuamb', 'repatha'],
    brandNames: ['Repatha'],
  },
  'ezetimibe': {
    correct: 'Ezetimibe',
    variations: ['esetimibe', 'exetimibe', 'zeetimibe', 'eeztimibe', 'ezteimibe', 'ezeitmibe', 'ezetmiibe', 'ezetiimbe', 'zetia'],
    brandNames: ['Zetia'],
  },
  'famotidine': {
    correct: 'Famotidine',
    variations: ['phamotidine', 'afmotidine', 'fmaotidine', 'faomtidine', 'famtoidine', 'famoitdine', 'famotdiine', 'famotiidne', 'pepcid'],
    brandNames: ['Pepcid'],
  },
  'fenofibrate': {
    correct: 'Fenofibrate',
    variations: ['phenophibrate', 'efnofibrate', 'fneofibrate', 'feonfibrate', 'fenfoibrate', 'fenoifbrate', 'fenofbirate', 'fenofirbate', 'tricor', 'trilipix'],
    brandNames: ['Tricor', 'Trilipix'],
  },
  'ferroussulfate': {
    correct: 'Ferrous Sulfate',
    variations: ['pherrous sulphate', 'ferous sulfate', 'efrrous sulfate', 'frerous sulfate', 'ferorus sulfate', 'ferruos sulfate', 'ferrosu sulfate', 'ferrou ssulfate'],
  },
  'fexofenadine': {
    correct: 'Fexofenadine',
    variations: ['phexophenadine', 'fezofenadine', 'efxofenadine', 'fxeofenadine', 'feoxfenadine', 'fexfoenadine', 'fexoefnadine', 'fexofneadine', 'allegra'],
    drugClass: 'Antihistamine',
    brandNames: ['Allegra'],
  },
  'finasteride': {
    correct: 'Finasteride',
    variations: ['phinasteride', 'ifnasteride', 'fniasteride', 'fiansteride', 'finsateride', 'finatseride', 'finasetride', 'finastreide', 'propecia', 'proscar'],
    drugClass: '5-Alpha Reductase Inhibitor',
    brandNames: ['Propecia', 'Proscar'],
  },
  'flecainide': {
    correct: 'Flecainide',
    variations: ['phlecainide', 'lfecainide', 'felcainide', 'flceainide', 'fleacinide', 'flecianide', 'flecaniide', 'flecaiinde', 'tambocor'],
    brandNames: ['Tambocor'],
  },
  'fluconazole': {
    correct: 'Fluconazole',
    variations: ['phluconazole', 'fluconasole', 'fluconaxole', 'lfuconazole', 'fulconazole', 'flcuonazole', 'fluocnazole', 'flucnoazole', 'diflucan'],
    brandNames: ['Diflucan'],
  },
  'fluorouracil': {
    correct: 'Fluorouracil',
    variations: ['phluorouracil', 'fluorourasil', 'lfuorouracil', 'fulorouracil', 'flourouracil', 'fluroouracil', 'fluooruracil', 'fluoruoracil'],
  },
  'fluoxetine': {
    correct: 'Fluoxetine',
    variations: ['phluoxetine', 'fluozetine', 'lfuoxetine', 'fuloxetine', 'flouxetine', 'fluxoetine', 'fluoextine', 'fluoxteine', 'prozac', 'sarafem'],
    drugClass: 'SSRI',
    brandNames: ['Prozac', 'Sarafem'],
  },
  'fluticasone': {
    correct: 'Fluticasone',
    variations: ['phluticasone', 'lfuticasone', 'fulticasone', 'fltuicasone', 'fluitcasone', 'flutciasone', 'flutiacsone', 'fluticsaone', 'flonase', 'flovent'],
    drugClass: 'Corticosteroid',
    brandNames: ['Flonase', 'Flovent'],
  },
  'folicacid': {
    correct: 'Folic Acid',
    variations: ['pholic acid', 'folic asid', 'oflic acid', 'floic acid', 'foilc acid', 'folci acid', 'foli cacid', 'folica cid'],
  },
  'furosemide': {
    correct: 'Furosemide',
    variations: ['phurosemide', 'furocemide', 'ufrosemide', 'fruosemide', 'fuorsemide', 'fursoemide', 'furoesmide', 'furosmeide', 'lasix'],
    drugClass: 'Loop Diuretic',
    brandNames: ['Lasix'],
  },
  'gabapentin': {
    correct: 'Gabapentin',
    variations: ['agbapentin', 'gbaapentin', 'gaabpentin', 'gabpaentin', 'gabaepntin', 'gabapnetin', 'gabapetnin', 'gabapenitn', 'neurontin', 'gralise'],
    drugClass: 'Anticonvulsant',
    brandNames: ['Neurontin', 'Gralise'],
  },
  'glimepiride': {
    correct: 'Glimepiride',
    variations: ['lgimepiride', 'gilmepiride', 'glmiepiride', 'gliempiride', 'glimpeiride', 'glimeipride', 'glimepriide', 'glimepiirde', 'amaryl'],
    drugClass: 'Sulfonylurea',
    brandNames: ['Amaryl'],
  },
  'glipizide': {
    correct: 'Glipizide',
    variations: ['glipiside', 'glipixide', 'lgipizide', 'gilpizide', 'glpiizide', 'gliipzide', 'glipziide', 'glipiizde', 'glucotrol'],
    drugClass: 'Sulfonylurea',
    brandNames: ['Glucotrol'],
  },
  'guaifenesin': {
    correct: 'Guaifenesin',
    variations: ['guaiphenesin', 'guaifenecin', 'ugaifenesin', 'gauifenesin', 'guiafenesin', 'guafienesin', 'guaiefnesin', 'guaifneesin', 'mucinex'],
    brandNames: ['Mucinex'],
  },
  'guanfacine': {
    correct: 'Guanfacine',
    variations: ['guanphacine', 'guanfasine', 'uganfacine', 'gaunfacine', 'gunafacine', 'guafnacine', 'guanafcine', 'guanfcaine', 'intuniv', 'tenex'],
    brandNames: ['Intuniv', 'Tenex'],
  },
  'hydralazine': {
    correct: 'Hydralazine',
    variations: ['hydralasine', 'hydralaxine', 'yhdralazine', 'hdyralazine', 'hyrdalazine', 'hydarlazine', 'hydrlaazine', 'hydraalzine', 'apresoline'],
    brandNames: ['Apresoline'],
  },
  'hydrochlorothiazide': {
    correct: 'Hydrochlorothiazide',
    variations: ['hydrochlorothiaside', 'hydrochlorothiaxide', 'yhdrochlorothiazide', 'hdyrochlorothiazide', 'hyrdochlorothiazide', 'hydorchlorothiazide', 'hydrcohlorothiazide', 'hydrohclorothiazide', 'microzide', 'hctz'],
    drugClass: 'Thiazide Diuretic',
    brandNames: ['Microzide', 'HCTZ'],
  },
  'hydrocortisone': {
    correct: 'Hydrocortisone',
    variations: ['yhdrocortisone', 'hdyrocortisone', 'hyrdocortisone', 'hydorcortisone', 'hydrcoortisone', 'hydroocrtisone', 'hydrocrotisone', 'hydrocotrisone', 'cortef'],
    drugClass: 'Corticosteroid',
    brandNames: ['Cortef'],
  },
  'hydroquinone': {
    correct: 'Hydroquinone',
    variations: ['yhdroquinone', 'hdyroquinone', 'hyrdoquinone', 'hydorquinone', 'hydrqouinone', 'hydrouqinone', 'hydroqiunone', 'hydroqunione'],
  },
  'hydroxychloroquine': {
    correct: 'Hydroxychloroquine',
    variations: ['hydrozychloroquine', 'yhdroxychloroquine', 'hdyroxychloroquine', 'hyrdoxychloroquine', 'hydorxychloroquine', 'hydrxoychloroquine', 'hydroyxchloroquine', 'hydroxcyhloroquine', 'plaquenil'],
    brandNames: ['Plaquenil'],
  },
  'hydroxyzine': {
    correct: 'Hydroxyzine',
    variations: ['hydroxysine', 'hydrozyzine', 'hydroxyxine', 'yhdroxyzine', 'hdyroxyzine', 'hyrdoxyzine', 'hydorxyzine', 'hydrxoyzine', 'atarax', 'vistaril'],
    drugClass: 'Antihistamine',
    brandNames: ['Atarax', 'Vistaril'],
  },
  'ibuprofen': {
    correct: 'Ibuprofen',
    variations: ['ibuprophen', 'biuprofen', 'iubprofen', 'ibpurofen', 'iburpofen', 'ibuporfen', 'ibuprfoen', 'ibuproefn', 'advil', 'motrin'],
    drugClass: 'NSAID',
    brandNames: ['Advil', 'Motrin'],
  },
  'indomethacin': {
    correct: 'Indomethacin',
    variations: ['indomethasin', 'nidomethacin', 'idnomethacin', 'inodmethacin', 'indmoethacin', 'indoemthacin', 'indomtehacin', 'indomehtacin', 'indocin'],
    drugClass: 'NSAID',
    brandNames: ['Indocin'],
  },
  'insulinaspart': {
    correct: 'Insulin Aspart',
    variations: ['nisulin aspart', 'isnulin aspart', 'inuslin aspart', 'insluin aspart', 'insuiln aspart', 'insulni aspart', 'insuli naspart', 'insulina spart'],
  },
  'insulindegludec': {
    correct: 'Insulin Degludec',
    variations: ['nisulin degludec', 'isnulin degludec', 'inuslin degludec', 'insluin degludec', 'insuiln degludec', 'insulni degludec', 'insuli ndegludec', 'insulind egludec'],
  },
  'insulindetemir': {
    correct: 'Insulin Detemir',
    variations: ['nisulin detemir', 'isnulin detemir', 'inuslin detemir', 'insluin detemir', 'insuiln detemir', 'insulni detemir', 'insuli ndetemir', 'insulind etemir'],
  },
  'insulinglargine': {
    correct: 'Insulin Glargine',
    variations: ['nisulin glargine', 'isnulin glargine', 'inuslin glargine', 'insluin glargine', 'insuiln glargine', 'insulni glargine', 'insuli nglargine', 'insuling largine'],
  },
  'insulinlispro': {
    correct: 'Insulin Lispro',
    variations: ['nisulin lispro', 'isnulin lispro', 'inuslin lispro', 'insluin lispro', 'insuiln lispro', 'insulni lispro', 'insuli nlispro', 'insulinl ispro'],
  },
  'ipratropium': {
    correct: 'Ipratropium',
    variations: ['piratropium', 'irpatropium', 'ipartropium', 'iprtaropium', 'iprartopium', 'ipratorpium', 'ipratrpoium', 'ipratroipum', 'atrovent'],
    drugClass: 'Anticholinergic Bronchodilator',
    brandNames: ['Atrovent'],
  },
  'irbesartan': {
    correct: 'Irbesartan',
    variations: ['ribesartan', 'ibresartan', 'irebsartan', 'irbseartan', 'irbeasrtan', 'irbesratan', 'irbesatran', 'irbesaratn', 'avapro'],
    drugClass: 'ARB',
    brandNames: ['Avapro'],
  },
  'isosorbide': {
    correct: 'Isosorbide',
    variations: ['siosorbide', 'iossorbide', 'issoorbide', 'isoosrbide', 'isosrobide', 'isosobride', 'isosoribde', 'isosorbdie', 'isordil', 'imdur'],
    brandNames: ['Isordil', 'Imdur'],
  },
  'ivermectin': {
    correct: 'Ivermectin',
    variations: ['viermectin', 'ievrmectin', 'ivremectin', 'ivemrectin', 'iveremctin', 'ivermcetin', 'ivermetcin', 'ivermecitn', 'stromectol'],
    brandNames: ['Stromectol'],
  },
  'ketoconazole': {
    correct: 'Ketoconazole',
    variations: ['ketoconasole', 'cetoconazole', 'ketoconaxole', 'ektoconazole', 'kteoconazole', 'keotconazole', 'ketcoonazole', 'ketoocnazole', 'nizoral'],
    brandNames: ['Nizoral'],
  },
  'ketorolac': {
    correct: 'Ketorolac',
    variations: ['cetorolac', 'ektorolac', 'kteorolac', 'keotrolac', 'ketroolac', 'ketoorlac', 'ketorloac', 'ketoroalc', 'toradol'],
    drugClass: 'NSAID',
    brandNames: ['Toradol'],
  },
  'ketotifen': {
    correct: 'Ketotifen',
    variations: ['ketotiphen', 'cetotifen', 'ektotifen', 'kteotifen', 'keottifen', 'kettoifen', 'ketoitfen', 'ketotfien'],
  },
  'labetalol': {
    correct: 'Labetalol',
    variations: ['albetalol', 'lbaetalol', 'laebtalol', 'labtealol', 'labeatlol', 'labetlaol', 'labetaoll', 'labetallo', 'trandate', 'normodyne'],
    drugClass: 'Beta-Blocker',
    brandNames: ['Trandate', 'Normodyne'],
  },
  'lactulose': {
    correct: 'Lactulose',
    variations: ['lactuloce', 'alctulose', 'lcatulose', 'latculose', 'lacutlose', 'lactluose', 'lactuolse', 'lactulsoe', 'enulose'],
    brandNames: ['Enulose'],
  },
  'lamotrigine': {
    correct: 'Lamotrigine',
    variations: ['almotrigine', 'lmaotrigine', 'laomtrigine', 'lamtorigine', 'lamortigine', 'lamotirgine', 'lamotrgiine', 'lamotriigne', 'lamictal'],
    drugClass: 'Anticonvulsant',
    brandNames: ['Lamictal'],
  },
  'latanoprost': {
    correct: 'Latanoprost',
    variations: ['altanoprost', 'ltaanoprost', 'laatnoprost', 'latnaoprost', 'lataonprost', 'latanporost', 'latanorpost', 'latanoporst', 'xalatan'],
    brandNames: ['Xalatan'],
  },
  'levetiracetam': {
    correct: 'Levetiracetam',
    variations: ['levetirasetam', 'elvetiracetam', 'lveetiracetam', 'leevtiracetam', 'levteiracetam', 'leveitracetam', 'levetriacetam', 'levetiarcetam', 'keppra'],
    drugClass: 'Anticonvulsant',
    brandNames: ['Keppra'],
  },
  'levocetirizine': {
    correct: 'Levocetirizine',
    variations: ['levosetirizine', 'levocetirisine', 'levocetirixine', 'elvocetirizine', 'lveocetirizine', 'leovcetirizine', 'levcoetirizine', 'levoectirizine', 'xyzal'],
    drugClass: 'Antihistamine',
    brandNames: ['Xyzal'],
  },
  'levofloxacin': {
    correct: 'Levofloxacin',
    variations: ['levophloxacin', 'levofloxasin', 'levoflozacin', 'elvofloxacin', 'lveofloxacin', 'leovfloxacin', 'levfoloxacin', 'levolfoxacin', 'levaquin'],
    drugClass: 'Fluoroquinolone',
    brandNames: ['Levaquin'],
  },
  'levothyroxine': {
    correct: 'Levothyroxine',
    variations: ['levothyrozine', 'elvothyroxine', 'lveothyroxine', 'leovthyroxine', 'levtohyroxine', 'levohtyroxine', 'levotyhroxine', 'levothryoxine', 'synthroid', 'levoxyl', 'unithroid'],
    drugClass: 'Thyroid Hormone',
    brandNames: ['Synthroid', 'Levoxyl', 'Unithroid'],
  },
  'lidocaine': {
    correct: 'Lidocaine',
    variations: ['ildocaine', 'ldiocaine', 'liodcaine', 'lidcoaine', 'lidoacine', 'lidociane', 'lidocanie', 'lidocaien', 'xylocaine'],
    brandNames: ['Xylocaine'],
  },
  'linaclotide': {
    correct: 'Linaclotide',
    variations: ['ilnaclotide', 'lniaclotide', 'lianclotide', 'lincalotide', 'linalcotide', 'linacoltide', 'linacltoide', 'linacloitde', 'linzess'],
    brandNames: ['Linzess'],
  },
  'linagliptin': {
    correct: 'Linagliptin',
    variations: ['ilnagliptin', 'lniagliptin', 'liangliptin', 'lingaliptin', 'linalgiptin', 'linagilptin', 'linaglpitin', 'linaglitpin', 'tradjenta'],
    drugClass: 'DPP-4 Inhibitor',
    brandNames: ['Tradjenta'],
  },
  'liothyronine': {
    correct: 'Liothyronine',
    variations: ['ilothyronine', 'loithyronine', 'litohyronine', 'liohtyronine', 'liotyhronine', 'liothryonine', 'liothyornine', 'liothyrnoine', 'cytomel'],
    drugClass: 'Thyroid Hormone',
    brandNames: ['Cytomel'],
  },
  'liraglutide': {
    correct: 'Liraglutide',
    variations: ['ilraglutide', 'lriaglutide', 'liarglutide', 'lirgalutide', 'liralgutide', 'liragultide', 'liragltuide', 'liragluitde', 'victoza', 'saxenda'],
    drugClass: 'GLP-1 Agonist',
    brandNames: ['Victoza', 'Saxenda'],
  },
  'lisdexamfetamine': {
    correct: 'Lisdexamfetamine',
    variations: ['lisdexamphetamine', 'lisdezamfetamine', 'ilsdexamfetamine', 'lsidexamfetamine', 'lidsexamfetamine', 'lisedxamfetamine', 'lisdxeamfetamine', 'lisdeaxmfetamine'],
    drugClass: 'Stimulant',
  },
  'lisinopril': {
    correct: 'Lisinopril',
    variations: ['licinopril', 'ilsinopril', 'lsiinopril', 'liisnopril', 'lisniopril', 'lisionpril', 'lisinporil', 'lisinorpil', 'prinivil', 'zestril'],
    drugClass: 'ACE Inhibitor',
    brandNames: ['Prinivil', 'Zestril'],
  },
  'lithium': {
    correct: 'Lithium',
    variations: ['llithhium', 'ilthium', 'ltihium', 'lihtium', 'litihum', 'lithuim', 'lithimu', 'lithobid'],
    brandNames: ['Lithobid'],
  },
  'loperamide': {
    correct: 'Loperamide',
    variations: ['olperamide', 'lpoeramide', 'loepramide', 'lopreamide', 'lopearmide', 'lopermaide', 'loperaimde', 'loperamdie', 'imodium'],
    brandNames: ['Imodium'],
  },
  'loratadine': {
    correct: 'Loratadine',
    variations: ['olratadine', 'lroatadine', 'loartadine', 'lortaadine', 'loraatdine', 'loratdaine', 'lorataidne', 'loratadnie', 'claritin'],
    drugClass: 'Antihistamine',
    brandNames: ['Claritin'],
  },
  'lorazepam': {
    correct: 'Lorazepam',
    variations: ['lorasepam', 'loraxepam', 'olrazepam', 'lroazepam', 'loarzepam', 'lorzaepam', 'loraezpam', 'lorazpeam', 'ativan'],
    drugClass: 'Benzodiazepine',
    brandNames: ['Ativan'],
  },
  'losartan': {
    correct: 'Losartan',
    variations: ['olsartan', 'lsoartan', 'loasrtan', 'losratan', 'losatran', 'losaratn', 'losartna', 'losarton', 'cozaar'],
    drugClass: 'ARB',
    brandNames: ['Cozaar'],
  },
  'lovastatin': {
    correct: 'Lovastatin',
    variations: ['olvastatin', 'lvoastatin', 'loavstatin', 'lovsatatin', 'lovatsatin', 'lovasattin', 'lovasttain', 'lovastaitn', 'mevacor'],
    drugClass: 'Statin',
    brandNames: ['Mevacor'],
  },
  'meclizine': {
    correct: 'Meclizine',
    variations: ['meclisine', 'meclixine', 'emclizine', 'mcelizine', 'melcizine', 'mecilzine', 'meclziine', 'mecliizne', 'antivert', 'bonine'],
    brandNames: ['Antivert', 'Bonine'],
  },
  'medroxyprogesterone': {
    correct: 'Medroxyprogesterone',
    variations: ['medrozyprogesterone', 'emdroxyprogesterone', 'mderoxyprogesterone', 'merdoxyprogesterone', 'medorxyprogesterone', 'medrxoyprogesterone', 'medroyxprogesterone', 'medroxpyrogesterone', 'provera', 'depo-provera', 'depoprovera'],
    brandNames: ['Provera', 'Depo-Provera'],
  },
  'melatonin': {
    correct: 'Melatonin',
    variations: ['emlatonin', 'mleatonin', 'mealtonin', 'meltaonin', 'melaotnin', 'melatnoin', 'melatoinn', 'melatonni'],
  },
  'meloxicam': {
    correct: 'Meloxicam',
    variations: ['melozicam', 'emloxicam', 'mleoxicam', 'meolxicam', 'melxoicam', 'meloixcam', 'meloxciam', 'meloxiacm', 'mobic'],
    drugClass: 'NSAID',
    brandNames: ['Mobic'],
  },
  'memantine': {
    correct: 'Memantine',
    variations: ['emmantine', 'mmeantine', 'meamntine', 'memnatine', 'mematnine', 'memanitne', 'memantnie', 'memantien', 'namenda'],
    drugClass: 'NMDA Receptor Antagonist',
    brandNames: ['Namenda'],
  },
  'mesalamine': {
    correct: 'Mesalamine',
    variations: ['emsalamine', 'msealamine', 'measlamine', 'meslaamine', 'mesaalmine', 'mesalmaine', 'mesalaimne', 'mesalamnie', 'asacol', 'pentasa'],
    brandNames: ['Asacol', 'Pentasa'],
  },
  'metformin': {
    correct: 'Metformin',
    variations: ['metphormin', 'emtformin', 'mteformin', 'meftormin', 'metofrmin', 'metfromin', 'metfomrin', 'metforimn', 'glucophage', 'fortamet', 'glumetza'],
    drugClass: 'Biguanide',
    brandNames: ['Glucophage', 'Fortamet', 'Glumetza'],
  },
  'methimazole': {
    correct: 'Methimazole',
    variations: ['methimasole', 'methimaxole', 'emthimazole', 'mtehimazole', 'mehtimazole', 'metihmazole', 'methmiazole', 'methiamzole', 'tapazole'],
    brandNames: ['Tapazole'],
  },
  'methocarbamol': {
    correct: 'Methocarbamol',
    variations: ['emthocarbamol', 'mtehocarbamol', 'mehtocarbamol', 'metohcarbamol', 'methcoarbamol', 'methoacrbamol', 'methocrabamol', 'methocabramol', 'robaxin'],
    drugClass: 'Muscle Relaxant',
    brandNames: ['Robaxin'],
  },
  'methotrexate': {
    correct: 'Methotrexate',
    variations: ['methotrezate', 'emthotrexate', 'mtehotrexate', 'mehtotrexate', 'metohtrexate', 'methtorexate', 'methortexate', 'methoterxate', 'rheumatrex', 'trexall'],
    brandNames: ['Rheumatrex', 'Trexall'],
  },
  'methylphenidate': {
    correct: 'Methylphenidate',
    variations: ['methylfenidate', 'emthylphenidate', 'mtehylphenidate', 'mehtylphenidate', 'metyhlphenidate', 'methlyphenidate', 'methyplhenidate', 'methylhpenidate', 'ritalin', 'concerta'],
    drugClass: 'Stimulant',
    brandNames: ['Ritalin', 'Concerta'],
  },
  'methylprednisolone': {
    correct: 'Methylprednisolone',
    variations: ['emthylprednisolone', 'mtehylprednisolone', 'mehtylprednisolone', 'metyhlprednisolone', 'methlyprednisolone', 'methyplrednisolone', 'methylrpednisolone', 'methylperdnisolone', 'medrol'],
    drugClass: 'Corticosteroid',
    brandNames: ['Medrol'],
  },
  'metoclopramide': {
    correct: 'Metoclopramide',
    variations: ['emtoclopramide', 'mteoclopramide', 'meotclopramide', 'metcolopramide', 'metolcopramide', 'metocolpramide', 'metoclporamide', 'metoclorpamide', 'reglan'],
    brandNames: ['Reglan'],
  },
  'metoprolol': {
    correct: 'Metoprolol',
    variations: ['emtoprolol', 'mteoprolol', 'meotprolol', 'metporolol', 'metorpolol', 'metoporlol', 'metoprlool', 'metoprooll', 'lopressor', 'toprol', 'toprol-xl', 'toprolxl'],
    drugClass: 'Beta-Blocker',
    brandNames: ['Lopressor', 'Toprol', 'Toprol-XL'],
  },
  'metronidazole': {
    correct: 'Metronidazole',
    variations: ['metronidasole', 'metronidaxole', 'emtronidazole', 'mteronidazole', 'mertonidazole', 'metornidazole', 'metrnoidazole', 'metroindazole', 'flagyl'],
    brandNames: ['Flagyl'],
  },
  'mirabegron': {
    correct: 'Mirabegron',
    variations: ['imrabegron', 'mriabegron', 'miarbegron', 'mirbaegron', 'miraebgron', 'mirabgeron', 'mirabergon', 'mirabegorn', 'myrbetriq'],
    brandNames: ['Myrbetriq'],
  },
  'mirtazapine': {
    correct: 'Mirtazapine',
    variations: ['mirtasapine', 'mirtaxapine', 'imrtazapine', 'mritazapine', 'mitrazapine', 'miratzapine', 'mirtzaapine', 'mirtaazpine', 'remeron'],
    brandNames: ['Remeron'],
  },
  'mometasone': {
    correct: 'Mometasone',
    variations: ['ommetasone', 'mmoetasone', 'moemtasone', 'momteasone', 'momeatsone', 'mometsaone', 'mometaosne', 'mometasnoe', 'nasonex', 'elocon'],
    drugClass: 'Corticosteroid',
    brandNames: ['Nasonex', 'Elocon'],
  },
  'montelukast': {
    correct: 'Montelukast',
    variations: ['montelucast', 'omntelukast', 'mnotelukast', 'motnelukast', 'monetlukast', 'montleukast', 'monteulkast', 'montelkuast', 'singulair'],
    drugClass: 'Leukotriene Receptor Antagonist',
    brandNames: ['Singulair'],
  },
  'morphine': {
    correct: 'Morphine',
    variations: ['morfine', 'omrphine', 'mrophine', 'moprhine', 'morhpine', 'morpihne', 'morphnie', 'morphien', 'ms contin', 'kadian'],
    drugClass: 'Opioid Analgesic',
    brandNames: ['MS Contin', 'Kadian'],
  },
  'moxifloxacin': {
    correct: 'Moxifloxacin',
    variations: ['moxiphloxacin', 'moxifloxasin', 'moziflozacin', 'omxifloxacin', 'mxoifloxacin', 'moixfloxacin', 'moxfiloxacin', 'moxilfoxacin', 'avelox'],
    drugClass: 'Fluoroquinolone',
    brandNames: ['Avelox'],
  },
  'mupirocin': {
    correct: 'Mupirocin',
    variations: ['mupirosin', 'umpirocin', 'mpuirocin', 'muiprocin', 'mupriocin', 'mupiorcin', 'mupircoin', 'mupiroicn', 'bactroban'],
    brandNames: ['Bactroban'],
  },
  'nabumetone': {
    correct: 'Nabumetone',
    variations: ['anbumetone', 'nbaumetone', 'naubmetone', 'nabmuetone', 'nabuemtone', 'nabumteone', 'nabumeotne', 'nabumetnoe', 'relafen'],
    drugClass: 'NSAID',
    brandNames: ['Relafen'],
  },
  'naproxen': {
    correct: 'Naproxen',
    variations: ['naprozen', 'anproxen', 'nparoxen', 'narpoxen', 'naporxen', 'naprxoen', 'naproexn', 'naproxne', 'aleve', 'naprosyn'],
    drugClass: 'NSAID',
    brandNames: ['Aleve', 'Naprosyn'],
  },
  'nebivolol': {
    correct: 'Nebivolol',
    variations: ['enbivolol', 'nbeivolol', 'neibvolol', 'nebviolol', 'nebiovlol', 'nebivlool', 'nebivooll', 'nebivollo', 'bystolic'],
    drugClass: 'Beta-Blocker',
    brandNames: ['Bystolic'],
  },
  'niacin': {
    correct: 'Niacin',
    variations: ['niasin', 'nniaccin', 'inacin', 'naicin', 'nicain', 'niaicn', 'niacni'],
  },
  'nifedipine': {
    correct: 'Nifedipine',
    variations: ['niphedipine', 'infedipine', 'nfiedipine', 'niefdipine', 'nifdeipine', 'nifeidpine', 'nifedpiine', 'nifediipne', 'procardia', 'adalat'],
    drugClass: 'Calcium Channel Blocker',
    brandNames: ['Procardia', 'Adalat'],
  },
  'nitrofurantoin': {
    correct: 'Nitrofurantoin',
    variations: ['nitrophurantoin', 'introfurantoin', 'ntirofurantoin', 'nirtofurantoin', 'nitorfurantoin', 'nitrfourantoin', 'nitroufrantoin', 'nitrofruantoin', 'macrobid', 'macrodantin'],
    brandNames: ['Macrobid', 'Macrodantin'],
  },
  'nitroglycerin': {
    correct: 'Nitroglycerin',
    variations: ['nitroglyserin', 'introglycerin', 'ntiroglycerin', 'nirtoglycerin', 'nitorglycerin', 'nitrgolycerin', 'nitrolgycerin', 'nitrogylcerin', 'nitrostat'],
    brandNames: ['Nitrostat'],
  },
  'norethindrone': {
    correct: 'Norethindrone',
    variations: ['onrethindrone', 'nroethindrone', 'noerthindrone', 'nortehindrone', 'norehtindrone', 'noretihndrone', 'norethnidrone', 'norethidnrone'],
  },
  'nortriptyline': {
    correct: 'Nortriptyline',
    variations: ['onrtriptyline', 'nrotriptyline', 'notrriptyline', 'norrtiptyline', 'nortirptyline', 'nortrpityline', 'nortritpyline', 'nortripytline', 'pamelor'],
    brandNames: ['Pamelor'],
  },
  'nystatin': {
    correct: 'Nystatin',
    variations: ['nysttattin', 'ynstatin', 'nsytatin', 'nytsatin', 'nysattin', 'nysttain', 'nystaitn', 'nystatni'],
  },
  'ofloxacin': {
    correct: 'Ofloxacin',
    variations: ['ophloxacin', 'ofloxasin', 'oflozacin', 'foloxacin', 'olfoxacin', 'ofolxacin', 'oflxoacin', 'ofloaxcin'],
  },
  'olanzapine': {
    correct: 'Olanzapine',
    variations: ['olansapine', 'olanxapine', 'loanzapine', 'oalnzapine', 'olnazapine', 'olaznapine', 'olanazpine', 'olanzpaine', 'zyprexa'],
    drugClass: 'Atypical Antipsychotic',
    brandNames: ['Zyprexa'],
  },
  'olmesartan': {
    correct: 'Olmesartan',
    variations: ['lomesartan', 'omlesartan', 'olemsartan', 'olmseartan', 'olmeasrtan', 'olmesratan', 'olmesatran', 'olmesaratn', 'benicar'],
    drugClass: 'ARB',
    brandNames: ['Benicar'],
  },
  'olopatadine': {
    correct: 'Olopatadine',
    variations: ['loopatadine', 'oolpatadine', 'olpoatadine', 'oloaptadine', 'oloptaadine', 'olopaatdine', 'olopatdaine', 'olopataidne', 'patanol', 'pataday'],
    brandNames: ['Patanol', 'Pataday'],
  },
  'omeprazole': {
    correct: 'Omeprazole',
    variations: ['omeprasole', 'omepraxole', 'moeprazole', 'oemprazole', 'omperazole', 'omerpazole', 'omeparzole', 'omeprzaole', 'prilosec'],
    drugClass: 'Proton Pump Inhibitor',
    brandNames: ['Prilosec'],
  },
  'ondansetron': {
    correct: 'Ondansetron',
    variations: ['ondancetron', 'nodansetron', 'odnansetron', 'onadnsetron', 'ondnasetron', 'ondasnetron', 'ondanestron', 'ondansteron', 'zofran'],
    brandNames: ['Zofran'],
  },
  'oseltamivir': {
    correct: 'Oseltamivir',
    variations: ['oceltamivir', 'soeltamivir', 'oesltamivir', 'osletamivir', 'osetlamivir', 'oselatmivir', 'oseltmaivir', 'oseltaimvir', 'tamiflu'],
    brandNames: ['Tamiflu'],
  },
  'oxcarbazepine': {
    correct: 'Oxcarbazepine',
    variations: ['oxcarbasepine', 'ozcarbazepine', 'oxcarbaxepine', 'xocarbazepine', 'ocxarbazepine', 'oxacrbazepine', 'oxcrabazepine', 'oxcabrazepine', 'trileptal'],
    drugClass: 'Anticonvulsant',
    brandNames: ['Trileptal'],
  },
  'oxybutynin': {
    correct: 'Oxybutynin',
    variations: ['ozybutynin', 'oxybbutynnin', 'xoybutynin', 'oyxbutynin', 'oxbyutynin', 'oxyubtynin', 'oxybtuynin', 'oxybuytnin', 'ditropan'],
    brandNames: ['Ditropan'],
  },
  'oxycodone': {
    correct: 'Oxycodone',
    variations: ['ozycodone', 'xoycodone', 'oyxcodone', 'oxcyodone', 'oxyocdone', 'oxycdoone', 'oxycoodne', 'oxycodnoe', 'oxycontin', 'roxicodone'],
    drugClass: 'Opioid Analgesic',
    brandNames: ['OxyContin', 'Roxicodone'],
  },
  'pancrelipase': {
    correct: 'Pancrelipase',
    variations: ['pancrelipace', 'apncrelipase', 'pnacrelipase', 'pacnrelipase', 'panrcelipase', 'pancerlipase', 'pancrleipase', 'pancreilpase'],
  },
  'pantoprazole': {
    correct: 'Pantoprazole',
    variations: ['pantoprasole', 'pantopraxole', 'apntoprazole', 'pnatoprazole', 'patnoprazole', 'panotprazole', 'pantporazole', 'pantorpazole', 'protonix'],
    drugClass: 'Proton Pump Inhibitor',
    brandNames: ['Protonix'],
  },
  'paroxetine': {
    correct: 'Paroxetine',
    variations: ['parozetine', 'aproxetine', 'praoxetine', 'paorxetine', 'parxoetine', 'paroextine', 'paroxteine', 'paroxeitne', 'paxil'],
    drugClass: 'SSRI',
    brandNames: ['Paxil'],
  },
  'penicillin': {
    correct: 'Penicillin',
    variations: ['penisillin', 'penicilin', 'epnicillin', 'pneicillin', 'peincillin', 'penciillin', 'peniicllin', 'peniclilin'],
  },
  'phenazopyridine': {
    correct: 'Phenazopyridine',
    variations: ['fenazopyridine', 'phenasopyridine', 'phenaxopyridine', 'hpenazopyridine', 'pehnazopyridine', 'phneazopyridine', 'pheanzopyridine', 'phenzaopyridine', 'pyridium', 'azo'],
    brandNames: ['Pyridium', 'AZO'],
  },
  'phentermine': {
    correct: 'Phentermine',
    variations: ['fentermine', 'hpentermine', 'pehntermine', 'phnetermine', 'phetnermine', 'phenetrmine', 'phentremine', 'phentemrine', 'adipex'],
    brandNames: ['Adipex'],
  },
  'pioglitazone': {
    correct: 'Pioglitazone',
    variations: ['pioglitasone', 'pioglitaxone', 'ipoglitazone', 'poiglitazone', 'pigolitazone', 'piolgitazone', 'piogiltazone', 'piogltiazone', 'actos'],
    drugClass: 'Thiazolidinedione',
    brandNames: ['Actos'],
  },
  'potassiumchloride': {
    correct: 'Potassium Chloride',
    variations: ['potascium chloride', 'potasium chloride', 'optassium chloride', 'ptoassium chloride', 'poatssium chloride', 'potsasium chloride', 'potasisum chloride', 'potassuim chloride'],
  },
  'pramipexole': {
    correct: 'Pramipexole',
    variations: ['pramipezole', 'rpamipexole', 'parmipexole', 'prmaipexole', 'praimpexole', 'prampiexole', 'pramiepxole', 'pramipxeole'],
  },
  'pravastatin': {
    correct: 'Pravastatin',
    variations: ['rpavastatin', 'parvastatin', 'prvaastatin', 'praavstatin', 'pravsatatin', 'pravatsatin', 'pravasattin', 'pravasttain', 'pravachol'],
    drugClass: 'Statin',
    brandNames: ['Pravachol'],
  },
  'prednisolone': {
    correct: 'Prednisolone',
    variations: ['rpednisolone', 'perdnisolone', 'prdenisolone', 'prendisolone', 'predinsolone', 'prednsiolone', 'prednioslone', 'prednisloone', 'prelone'],
    drugClass: 'Corticosteroid',
    brandNames: ['Prelone'],
  },
  'prednisone': {
    correct: 'Prednisone',
    variations: ['rpednisone', 'perdnisone', 'prdenisone', 'prendisone', 'predinsone', 'prednsione', 'predniosne', 'prednisnoe', 'deltasone', 'rayos'],
    drugClass: 'Corticosteroid',
    brandNames: ['Deltasone', 'Rayos'],
  },
  'pregabalin': {
    correct: 'Pregabalin',
    variations: ['rpegabalin', 'pergabalin', 'prgeabalin', 'preagbalin', 'pregbaalin', 'pregaablin', 'pregablain', 'pregabailn', 'lyrica'],
    drugClass: 'Anticonvulsant',
    brandNames: ['Lyrica'],
  },
  'primidone': {
    correct: 'Primidone',
    variations: ['rpimidone', 'pirmidone', 'prmiidone', 'priimdone', 'primdione', 'primiodne', 'primidnoe', 'primidoen'],
  },
  'progesterone': {
    correct: 'Progesterone',
    variations: ['rpogesterone', 'porgesterone', 'prgoesterone', 'proegsterone', 'progseterone', 'progetserone', 'progesetrone', 'progestreone'],
  },
  'promethazine': {
    correct: 'Promethazine',
    variations: ['promethasine', 'promethaxine', 'rpomethazine', 'pormethazine', 'prmoethazine', 'proemthazine', 'promtehazine', 'promehtazine', 'phenergan'],
    drugClass: 'Antihistamine',
    brandNames: ['Phenergan'],
  },
  'propranolol': {
    correct: 'Propranolol',
    variations: ['rpopranolol', 'porpranolol', 'prporanolol', 'prorpanolol', 'proparnolol', 'proprnaolol', 'propraonlol', 'propranlool', 'inderal'],
    drugClass: 'Beta-Blocker',
    brandNames: ['Inderal'],
  },
  'pseudoephedrine': {
    correct: 'Pseudoephedrine',
    variations: ['pseudoefedrine', 'pceudoephedrine', 'speudoephedrine', 'pesudoephedrine', 'psuedoephedrine', 'pseduoephedrine', 'pseuodephedrine', 'pseudeophedrine', 'sudafed'],
    brandNames: ['Sudafed'],
  },
  'quetiapine': {
    correct: 'Quetiapine',
    variations: ['uqetiapine', 'qeutiapine', 'quteiapine', 'queitapine', 'quetaipine', 'quetipaine', 'quetiaipne', 'quetiapnie', 'seroquel'],
    drugClass: 'Atypical Antipsychotic',
    brandNames: ['Seroquel'],
  },
  'ramipril': {
    correct: 'Ramipril',
    variations: ['armipril', 'rmaipril', 'raimpril', 'rampiril', 'ramirpil', 'ramipirl', 'ramiprli', 'ramiprill', 'altace'],
    drugClass: 'ACE Inhibitor',
    brandNames: ['Altace'],
  },
  'riboflavin': {
    correct: 'Riboflavin',
    variations: ['ribophlavin', 'irboflavin', 'rbioflavin', 'riobflavin', 'ribfolavin', 'ribolfavin', 'ribofalvin', 'riboflvain'],
  },
  'rimegepant': {
    correct: 'Rimegepant',
    variations: ['irmegepant', 'rmiegepant', 'riemgepant', 'rimgeepant', 'rimeegpant', 'rimegpeant', 'rimegeapnt', 'rimegepnat'],
  },
  'risperidone': {
    correct: 'Risperidone',
    variations: ['irsperidone', 'rsiperidone', 'ripseridone', 'risepridone', 'rispreidone', 'rispeirdone', 'risperdione', 'risperiodne', 'risperdal'],
    drugClass: 'Atypical Antipsychotic',
    brandNames: ['Risperdal'],
  },
  'rivaroxaban': {
    correct: 'Rivaroxaban',
    variations: ['rivarozaban', 'irvaroxaban', 'rviaroxaban', 'riavroxaban', 'rivraoxaban', 'rivaorxaban', 'rivarxoaban', 'rivaroaxban', 'xarelto'],
    drugClass: 'Anticoagulant',
    brandNames: ['Xarelto'],
  },
  'rizatriptan': {
    correct: 'Rizatriptan',
    variations: ['risatriptan', 'rixatriptan', 'irzatriptan', 'rziatriptan', 'riaztriptan', 'riztariptan', 'rizartiptan', 'rizatirptan', 'maxalt'],
    brandNames: ['Maxalt'],
  },
  'ropinirole': {
    correct: 'Ropinirole',
    variations: ['orpinirole', 'rpoinirole', 'roipnirole', 'ropniirole', 'ropiinrole', 'ropinriole', 'ropiniorle', 'ropinirloe', 'requip'],
    brandNames: ['Requip'],
  },
  'rosuvastatin': {
    correct: 'Rosuvastatin',
    variations: ['orsuvastatin', 'rsouvastatin', 'rousvastatin', 'rosvuastatin', 'rosuavstatin', 'rosuvsatatin', 'rosuvatsatin', 'rosuvasattin', 'crestor'],
    drugClass: 'Statin',
    brandNames: ['Crestor'],
  },
  'semaglutide': {
    correct: 'Semaglutide',
    variations: ['cemaglutide', 'esmaglutide', 'smeaglutide', 'seamglutide', 'semgalutide', 'semalgutide', 'semagultide', 'semagltuide', 'ozempic', 'wegovy', 'rybelsus'],
    drugClass: 'GLP-1 Agonist',
    brandNames: ['Ozempic', 'Wegovy', 'Rybelsus'],
  },
  'sertraline': {
    correct: 'Sertraline',
    variations: ['certraline', 'esrtraline', 'sretraline', 'setrraline', 'serrtaline', 'sertarline', 'sertrlaine', 'sertrailne', 'zoloft'],
    drugClass: 'SSRI',
    brandNames: ['Zoloft'],
  },
  'sildenafil': {
    correct: 'Sildenafil',
    variations: ['sildenaphil', 'cildenafil', 'isldenafil', 'slidenafil', 'sidlenafil', 'silednafil', 'sildneafil', 'sildeanfil', 'viagra', 'revatio'],
    drugClass: 'PDE5 Inhibitor',
    brandNames: ['Viagra', 'Revatio'],
  },
  'simvastatin': {
    correct: 'Simvastatin',
    variations: ['cimvastatin', 'ismvastatin', 'smivastatin', 'sivmastatin', 'simavstatin', 'simvsatatin', 'simvatsatin', 'simvasattin', 'zocor'],
    drugClass: 'Statin',
    brandNames: ['Zocor'],
  },
  'sitagliptin': {
    correct: 'Sitagliptin',
    variations: ['citagliptin', 'istagliptin', 'stiagliptin', 'siatgliptin', 'sitgaliptin', 'sitalgiptin', 'sitagilptin', 'sitaglpitin', 'januvia'],
    drugClass: 'DPP-4 Inhibitor',
    brandNames: ['Januvia'],
  },
  'sodiumfluoride': {
    correct: 'Sodium Fluoride',
    variations: ['sodium phluoride', 'osdium fluoride', 'sdoium fluoride', 'soidum fluoride', 'soduim fluoride', 'sodimu fluoride', 'sodiu mfluoride', 'sodiumf luoride'],
  },
  'solifenacin': {
    correct: 'Solifenacin',
    variations: ['soliphenacin', 'solifenasin', 'oslifenacin', 'sloifenacin', 'soilfenacin', 'solfienacin', 'soliefnacin', 'solifneacin', 'vesicare'],
    brandNames: ['Vesicare'],
  },
  'spironolactone': {
    correct: 'Spironolactone',
    variations: ['psironolactone', 'sipronolactone', 'sprionolactone', 'spiornolactone', 'spirnoolactone', 'spiroonlactone', 'spironloactone', 'spironoalctone', 'aldactone'],
    drugClass: 'Potassium-Sparing Diuretic',
    brandNames: ['Aldactone'],
  },
  'sucralfate': {
    correct: 'Sucralfate',
    variations: ['sucralphate', 'uscralfate', 'scuralfate', 'surcalfate', 'sucarlfate', 'sucrlafate', 'sucraflate', 'sucralafte', 'carafate'],
    brandNames: ['Carafate'],
  },
  'sumatriptan': {
    correct: 'Sumatriptan',
    variations: ['usmatriptan', 'smuatriptan', 'suamtriptan', 'sumtariptan', 'sumartiptan', 'sumatirptan', 'sumatrpitan', 'sumatritpan', 'imitrex'],
    brandNames: ['Imitrex'],
  },
  'tadalafil': {
    correct: 'Tadalafil',
    variations: ['tadalaphil', 'atdalafil', 'tdaalafil', 'taadlafil', 'tadlaafil', 'tadaalfil', 'tadalfail', 'tadalaifl', 'cialis', 'adcirca'],
    drugClass: 'PDE5 Inhibitor',
    brandNames: ['Cialis', 'Adcirca'],
  },
  'tamsulosin': {
    correct: 'Tamsulosin',
    variations: ['tamsulocin', 'atmsulosin', 'tmasulosin', 'tasmulosin', 'tamuslosin', 'tamsluosin', 'tamsuolsin', 'tamsulsoin', 'flomax'],
    drugClass: 'Alpha Blocker',
    brandNames: ['Flomax'],
  },
  'telmisartan': {
    correct: 'Telmisartan',
    variations: ['etlmisartan', 'tlemisartan', 'temlisartan', 'telimsartan', 'telmsiartan', 'telmiasrtan', 'telmisratan', 'telmisatran', 'micardis'],
    drugClass: 'ARB',
    brandNames: ['Micardis'],
  },
  'terazosin': {
    correct: 'Terazosin',
    variations: ['terazocin', 'terasosin', 'teraxosin', 'etrazosin', 'treazosin', 'tearzosin', 'terzaosin', 'teraozsin', 'hytrin'],
    drugClass: 'Alpha Blocker',
    brandNames: ['Hytrin'],
  },
  'terbinafine': {
    correct: 'Terbinafine',
    variations: ['terbinaphine', 'etrbinafine', 'trebinafine', 'tebrinafine', 'teribnafine', 'terbniafine', 'terbianfine', 'terbinfaine', 'lamisil'],
    brandNames: ['Lamisil'],
  },
  'testosterone': {
    correct: 'Testosterone',
    variations: ['etstosterone', 'tsetosterone', 'tetsosterone', 'tesotsterone', 'testsoterone', 'testotserone', 'testosetrone', 'testostreone'],
  },
  'thyroid': {
    correct: 'Thyroid',
    variations: ['thyrroid', 'htyroid', 'tyhroid', 'thryoid', 'thyorid', 'thyriod', 'thyrodi'],
    drugClass: 'Thyroid Hormone',
  },
  'ticagrelor': {
    correct: 'Ticagrelor',
    variations: ['itcagrelor', 'tciagrelor', 'tiacgrelor', 'ticgarelor', 'ticargelor', 'ticagerlor', 'ticagrleor', 'ticagreolr', 'brilinta'],
    drugClass: 'Antiplatelet',
    brandNames: ['Brilinta'],
  },
  'timolol': {
    correct: 'Timolol',
    variations: ['itmolol', 'tmiolol', 'tiomlol', 'timlool', 'timooll', 'timollo', 'timalol', 'timololol', 'timoptic'],
    brandNames: ['Timoptic'],
  },
  'tiotropium': {
    correct: 'Tiotropium',
    variations: ['itotropium', 'toitropium', 'titoropium', 'tiortopium', 'tiotorpium', 'tiotrpoium', 'tiotroipum', 'tiotropuim', 'spiriva'],
    drugClass: 'Anticholinergic Bronchodilator',
    brandNames: ['Spiriva'],
  },
  'tirzepatide': {
    correct: 'Tirzepatide',
    variations: ['tirsepatide', 'tirxepatide', 'itrzepatide', 'trizepatide', 'tizrepatide', 'tirezpatide', 'tirzpeatide', 'tirzeaptide', 'mounjaro', 'zepbound'],
    drugClass: 'GLP-1 Agonist',
    brandNames: ['Mounjaro', 'Zepbound'],
  },
  'tizanidine': {
    correct: 'Tizanidine',
    variations: ['tisanidine', 'tixanidine', 'itzanidine', 'tzianidine', 'tiaznidine', 'tiznaidine', 'tizaindine', 'tizandiine', 'zanaflex'],
    drugClass: 'Muscle Relaxant',
    brandNames: ['Zanaflex'],
  },
  'tobramycin': {
    correct: 'Tobramycin',
    variations: ['tobramysin', 'otbramycin', 'tboramycin', 'torbamycin', 'tobarmycin', 'tobrmaycin', 'tobraymcin', 'tobramcyin', 'tobrex'],
    brandNames: ['Tobrex'],
  },
  'topiramate': {
    correct: 'Topiramate',
    variations: ['otpiramate', 'tpoiramate', 'toipramate', 'topriamate', 'topiarmate', 'topirmaate', 'topiraamte', 'topiramtae', 'topamax'],
    drugClass: 'Anticonvulsant',
    brandNames: ['Topamax'],
  },
  'torsemide': {
    correct: 'Torsemide',
    variations: ['torcemide', 'otrsemide', 'trosemide', 'tosremide', 'toresmide', 'torsmeide', 'torseimde', 'torsemdie', 'demadex'],
    drugClass: 'Loop Diuretic',
    brandNames: ['Demadex'],
  },
  'tramadol': {
    correct: 'Tramadol',
    variations: ['rtamadol', 'tarmadol', 'trmaadol', 'traamdol', 'tramdaol', 'tramaodl', 'tramadlo', 'ultram', 'conzip'],
    drugClass: 'Opioid Analgesic',
    brandNames: ['Ultram', 'ConZip'],
  },
  'trazodone': {
    correct: 'Trazodone',
    variations: ['trasodone', 'traxodone', 'rtazodone', 'tarzodone', 'trzaodone', 'traozdone', 'trazdoone', 'trazoodne', 'desyrel'],
    brandNames: ['Desyrel'],
  },
  'tretinoin': {
    correct: 'Tretinoin',
    variations: ['rtetinoin', 'tertinoin', 'trteinoin', 'treitnoin', 'tretnioin', 'tretionin', 'tretinion', 'tretinoni', 'retin-a', 'retina'],
    brandNames: ['Retin-A'],
  },
  'triamcinolone': {
    correct: 'Triamcinolone',
    variations: ['triamsinolone', 'rtiamcinolone', 'tiramcinolone', 'traimcinolone', 'trimacinolone', 'triacminolone', 'triamicnolone', 'triamcniolone', 'kenalog', 'aristocort'],
    drugClass: 'Corticosteroid',
    brandNames: ['Kenalog', 'Aristocort'],
  },
  'valacyclovir': {
    correct: 'Valacyclovir',
    variations: ['avlacyclovir', 'vlaacyclovir', 'vaalcyclovir', 'valcayclovir', 'valaycclovir', 'valaccylovir', 'valacylcovir', 'valacycolvir', 'valtrex'],
    brandNames: ['Valtrex'],
  },
  'valproate': {
    correct: 'Valproate',
    variations: ['avlproate', 'vlaproate', 'vaplroate', 'valrpoate', 'valporate', 'valpraote', 'valprotae', 'valproaet'],
    drugClass: 'Anticonvulsant',
  },
  'valsartan': {
    correct: 'Valsartan',
    variations: ['avlsartan', 'vlasartan', 'vaslartan', 'valasrtan', 'valsratan', 'valsatran', 'valsaratn', 'valsartna', 'diovan'],
    drugClass: 'ARB',
    brandNames: ['Diovan'],
  },
  'venlafaxine': {
    correct: 'Venlafaxine',
    variations: ['venlaphaxine', 'venlafazine', 'evnlafaxine', 'vnelafaxine', 'velnafaxine', 'venalfaxine', 'venlfaaxine', 'venlaafxine', 'effexor'],
    drugClass: 'SNRI',
    brandNames: ['Effexor'],
  },
  'verapamil': {
    correct: 'Verapamil',
    variations: ['evrapamil', 'vreapamil', 'vearpamil', 'verpaamil', 'veraapmil', 'verapmail', 'verapaiml', 'verapamli', 'calan', 'verelan'],
    drugClass: 'Calcium Channel Blocker',
    brandNames: ['Calan', 'Verelan'],
  },
  'vitamine': {
    correct: 'Vitamin E',
    variations: ['ivtamin e', 'vtiamin e', 'viatmin e', 'vitmain e', 'vitaimn e', 'vitamni e', 'vitami ne', 'vitamine '],
  },
  'warfarin': {
    correct: 'Warfarin',
    variations: ['warpharin', 'awrfarin', 'wrafarin', 'wafrarin', 'warafrin', 'warfrain', 'warfairn', 'warfarni', 'coumadin', 'jantoven'],
    drugClass: 'Anticoagulant',
    brandNames: ['Coumadin', 'Jantoven'],
  },
  'zolpidem': {
    correct: 'Zolpidem',
    variations: ['solpidem', 'xolpidem', 'ozlpidem', 'zlopidem', 'zoplidem', 'zolipdem', 'zolpdiem', 'zolpiedm', 'ambien'],
    brandNames: ['Ambien'],
  }
};

/**
 * Auto-generated corrections map for fast lookup
 * Maps all variations (including brand names) to correct generic name
 */
export const MEDICATION_CORRECTIONS: Record<string, string> = {};
Object.entries(MEDICATION_DATABASE).forEach(([key, data]) => {
  MEDICATION_CORRECTIONS[key] = data.correct;
  data.variations.forEach(variant => {
    MEDICATION_CORRECTIONS[variant.toLowerCase()] = data.correct;
  });
});


// Generated 253 medications with variations
