/**
 * Caregiver Email Service
 * 
 * Handles sending visit summary PDFs to registered caregivers.
 */

import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import { Resend } from 'resend';
import PdfPrinter from 'pdfmake';
import type { TDocumentDefinitions } from 'pdfmake/interfaces';

const getDb = () => admin.firestore();

// Initialize Resend
const getResend = () => {
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
        throw new Error('RESEND_API_KEY not configured');
    }
    return new Resend(apiKey);
};

// Fonts for PDF
const fonts = {
    Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique',
    },
};

interface VisitPDFData {
    visitId: string;
    patientName: string;
    visitDate: Date;
    provider: string;
    summary: string;
    diagnoses: string[];
    medications: { started?: unknown[]; stopped?: unknown[]; changed?: unknown[] };
    nextSteps: string[];
}

/**
 * Generate a visit summary PDF for caregivers
 */
async function generateVisitPDF(data: VisitPDFData): Promise<Buffer> {
    const printer = new PdfPrinter(fonts);

    const formatDateStr = (date: Date) => date.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });

    // Build medication section
    const medContent: unknown[] = [];
    const meds = data.medications;
    if (meds.started && meds.started.length > 0) {
        medContent.push({ text: 'New Medications:', style: 'subheader', margin: [0, 10, 0, 5] });
        medContent.push({ ul: meds.started.map(m => formatMed(m)) });
    }
    if (meds.stopped && meds.stopped.length > 0) {
        medContent.push({ text: 'Stopped Medications:', style: 'subheader', margin: [0, 10, 0, 5] });
        medContent.push({ ul: meds.stopped.map(m => formatMed(m)) });
    }
    if (meds.changed && meds.changed.length > 0) {
        medContent.push({ text: 'Changed Medications:', style: 'subheader', margin: [0, 10, 0, 5] });
        medContent.push({ ul: meds.changed.map(m => formatMed(m)) });
    }

    // Build content array
    const content: unknown[] = [
        // Header
        { text: 'LumiMD', style: 'brand', alignment: 'center' },
        { text: 'Visit Summary', style: 'subtitle', alignment: 'center', margin: [0, 0, 0, 20] },

        // Visit info
        {
            columns: [
                { text: [{ text: 'Patient: ', bold: true }, data.patientName], width: '*' },
                { text: formatDateStr(data.visitDate), alignment: 'right', width: 'auto' },
            ],
            margin: [0, 0, 0, 5],
        },
        { text: [{ text: 'Provider: ', bold: true }, data.provider], margin: [0, 0, 0, 15] },
    ];

    // Summary
    if (data.summary) {
        content.push({ text: 'Summary', style: 'header' });
        content.push({ text: data.summary, margin: [0, 5, 0, 15] });
    }

    // Diagnoses
    if (data.diagnoses.length > 0) {
        content.push({ text: 'Discussed Conditions', style: 'header' });
        content.push({ ul: data.diagnoses, margin: [0, 5, 0, 15] });
    }

    // Medications
    if (medContent.length > 0) {
        content.push({ text: 'Medication Changes', style: 'header' });
        content.push(...medContent);
        content.push({ text: '', margin: [0, 0, 0, 15] });
    }

    // Next steps
    if (data.nextSteps.length > 0) {
        content.push({ text: 'Action Items', style: 'header' });
        content.push({ ul: data.nextSteps, margin: [0, 5, 0, 15] });
    }

    // Footer
    content.push({ text: '', margin: [0, 20, 0, 0] });
    content.push({ text: 'This summary was generated by LumiMD.', style: 'footer', alignment: 'center' });
    content.push({ text: 'Visit portal.lumimd.app for full details.', style: 'footer', alignment: 'center' });

    const docDefinition = {
        content,
        styles: {
            brand: { fontSize: 24, bold: true, color: '#078A94' },
            subtitle: { fontSize: 14, color: '#64748B' },
            header: { fontSize: 14, bold: true, color: '#1E293B', margin: [0, 10, 0, 5] },
            subheader: { fontSize: 12, bold: true, color: '#475569' },
            footer: { fontSize: 10, color: '#94A3B8' },
        },
        defaultStyle: {
            font: 'Helvetica',
            fontSize: 11,
            color: '#334155',
        },
    } as TDocumentDefinitions;

    return new Promise((resolve, reject) => {
        try {
            const pdfDoc = printer.createPdfKitDocument(docDefinition);
            const chunks: Buffer[] = [];
            pdfDoc.on('data', (chunk: Buffer) => chunks.push(chunk));
            pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
            pdfDoc.on('error', reject);
            pdfDoc.end();
        } catch (error) {
            reject(error);
        }
    });
}

function formatMed(med: unknown): string {
    if (typeof med === 'string') return med;
    if (typeof med === 'object' && med !== null) {
        const m = med as { name?: string; dose?: string; display?: string };
        return m.display || (m.dose ? `${m.name} (${m.dose})` : m.name || 'Unknown');
    }
    return 'Unknown';
}

interface Caregiver {
    id: string;
    name: string;
    email: string;
    relationship?: string;
    status: 'pending' | 'active' | 'paused';
    shareUserId?: string;
}

interface ShareResult {
    caregiverId: string;
    email: string;
    success: boolean;
    error?: string;
}

/**
 * Send a visit summary PDF to a single caregiver
 */
export async function sendVisitPdfToCaregiver(
    userId: string,
    visitId: string,
    caregiver: Caregiver
): Promise<ShareResult> {
    const result: ShareResult = {
        caregiverId: caregiver.id,
        email: caregiver.email,
        success: false,
    };

    // Skip if caregiver has paused emails
    if (caregiver.status === 'paused') {
        result.error = 'Caregiver has paused email updates';
        return result;
    }

    try {
        // Get visit data
        const visitDoc = await getDb().collection('visits').doc(visitId).get();
        if (!visitDoc.exists) {
            result.error = 'Visit not found';
            return result;
        }

        const visit = visitDoc.data()!;
        if (visit.userId !== userId) {
            result.error = 'Visit does not belong to user';
            return result;
        }

        // Get patient info
        const userDoc = await getDb().collection('users').doc(userId).get();
        const userData = userDoc.exists ? userDoc.data() : {};
        const patientName = userData?.firstName
            ? `${userData.firstName}${userData.lastName ? ' ' + userData.lastName : ''}`
            : 'Your Patient';

        // Generate PDF
        const pdfBuffer = await generateVisitPDF({
            visitId,
            patientName,
            visitDate: visit.visitDate?.toDate?.() || visit.createdAt?.toDate?.() || new Date(),
            provider: visit.provider || 'Provider',
            summary: visit.summary || '',
            diagnoses: visit.diagnoses || [],
            medications: visit.medications || { started: [], stopped: [], changed: [] },
            nextSteps: visit.nextSteps || [],
        });

        // Format visit date for email
        const visitDate = visit.visitDate?.toDate?.() || visit.createdAt?.toDate?.() || new Date();
        const formattedDate = visitDate.toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
        });

        // Generate portal link
        const portalBaseUrl = process.env.WEB_PORTAL_URL || 'https://portal.lumimd.app';
        const portalLink = `${portalBaseUrl}/shared/${userId}/visits/${visitId}`;

        // Build email content
        const emailHtml = buildCaregiverEmailHtml({
            caregiverName: caregiver.name,
            patientName,
            visitDate: formattedDate,
            provider: visit.provider || 'their healthcare provider',
            summary: visit.summary || '',
            diagnoses: visit.diagnoses || [],
            medications: visit.medications || { started: [], stopped: [], changed: [] },
            nextSteps: visit.nextSteps || [],
            portalLink,
        });

        // Send email
        const resend = getResend();
        await resend.emails.send({
            from: 'LumiMD <updates@lumimd.app>',
            to: caregiver.email,
            subject: `Visit Summary for ${patientName} - ${formattedDate}`,
            html: emailHtml,
            attachments: [
                {
                    filename: `Visit_Summary_${visitDate.toISOString().split('T')[0]}.pdf`,
                    content: pdfBuffer.toString('base64'),
                },
            ],
        });

        // Log the email
        await getDb().collection('caregiverEmailLog').add({
            userId,
            caregiverId: caregiver.id,
            caregiverEmail: caregiver.email,
            visitId,
            sentAt: admin.firestore.Timestamp.now(),
            status: 'sent',
        });

        functions.logger.info('[caregiverEmail] Sent visit PDF', {
            userId,
            visitId,
            caregiverId: caregiver.id,
            email: caregiver.email,
        });

        result.success = true;
        return result;

    } catch (error) {
        result.error = error instanceof Error ? error.message : 'Unknown error';

        // Log failed attempt
        await getDb().collection('caregiverEmailLog').add({
            userId,
            caregiverId: caregiver.id,
            caregiverEmail: caregiver.email,
            visitId,
            sentAt: admin.firestore.Timestamp.now(),
            status: 'failed',
            errorMessage: result.error,
        });

        functions.logger.error('[caregiverEmail] Failed to send visit PDF', {
            userId,
            visitId,
            caregiverId: caregiver.id,
            error: result.error,
        });

        return result;
    }
}

/**
 * Send a visit summary PDF to all active caregivers for a user
 */
export async function sendVisitPdfToAllCaregivers(
    userId: string,
    visitId: string,
    caregiverIds?: string[] // If provided, only send to these caregivers
): Promise<{
    sent: number;
    failed: number;
    results: ShareResult[];
}> {
    // Get user's caregivers
    const userDoc = await getDb().collection('users').doc(userId).get();
    if (!userDoc.exists) {
        return { sent: 0, failed: 0, results: [] };
    }

    const userData = userDoc.data() || {};
    let caregivers: Caregiver[] = Array.isArray(userData.caregivers) ? userData.caregivers : [];

    // Filter to specific caregivers if provided
    if (caregiverIds && caregiverIds.length > 0) {
        caregivers = caregivers.filter(c => caregiverIds.includes(c.id));
    }

    // Filter out paused caregivers
    const activeCaregivers = caregivers.filter(c => c.status !== 'paused');

    if (activeCaregivers.length === 0) {
        return { sent: 0, failed: 0, results: [] };
    }

    // Send to each caregiver
    const results: ShareResult[] = [];
    for (const caregiver of activeCaregivers) {
        const result = await sendVisitPdfToCaregiver(userId, visitId, caregiver);
        results.push(result);
    }

    const sent = results.filter(r => r.success).length;
    const failed = results.filter(r => !r.success).length;

    functions.logger.info('[caregiverEmail] Batch send complete', {
        userId,
        visitId,
        sent,
        failed,
        total: activeCaregivers.length,
    });

    return { sent, failed, results };
}

/**
 * Send caregiver invite email when they are added
 */
export async function sendCaregiverInviteEmail(
    userId: string,
    caregiver: Caregiver
): Promise<boolean> {
    try {
        const userDoc = await getDb().collection('users').doc(userId).get();
        const userData = userDoc.exists ? userDoc.data() : {};
        const patientName = userData?.firstName
            ? `${userData.firstName}${userData.lastName ? ' ' + userData.lastName : ''}`
            : 'Your patient';

        const portalBaseUrl = process.env.WEB_PORTAL_URL || 'https://portal.lumimd.app';
        const signupLink = `${portalBaseUrl}/signup?invite=caregiver&from=${encodeURIComponent(patientName)}`;

        const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>You've been added as a caregiver on LumiMD</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #f5f5f5;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; padding: 40px 20px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; background-color: white; border-radius: 12px; overflow: hidden;">
          
          <!-- Header -->
          <tr>
            <td style="background: linear-gradient(135deg, #078A94 0%, #40C9D0 100%); padding: 32px; text-align: center;">
              <h1 style="color: white; margin: 0; font-size: 24px; font-weight: 600;">LumiMD</h1>
            </td>
          </tr>
          
          <!-- Content -->
          <tr>
            <td style="padding: 40px;">
              <h2 style="color: #1E293B; margin: 0 0 16px 0; font-size: 20px; font-weight: 600;">
                Hi ${caregiver.name},
              </h2>
              
              <p style="color: #475569; font-size: 16px; line-height: 1.6; margin: 0 0 24px 0;">
                <strong>${patientName}</strong> has added you as a caregiver on LumiMD. You'll receive email summaries after each of their medical visits.
              </p>
              
              <p style="color: #475569; font-size: 16px; line-height: 1.6; margin: 0 0 24px 0;">
                To access detailed visit history and the full care portal, create your free account:
              </p>
              
              <div style="text-align: center; margin: 32px 0;">
                <a href="${signupLink}" style="display: inline-block; background-color: #078A94; color: white; text-decoration: none; padding: 14px 32px; border-radius: 8px; font-weight: 600; font-size: 16px;">
                  Create Your Account
                </a>
              </div>
              
              <p style="color: #94A3B8; font-size: 14px; line-height: 1.5; margin: 24px 0 0 0;">
                You'll still receive visit summaries by email even without an account.
              </p>
            </td>
          </tr>
          
          <!-- Footer -->
          <tr>
            <td style="background-color: #F8FAFC; padding: 24px 40px; border-top: 1px solid #E2E8F0;">
              <p style="color: #94A3B8; font-size: 12px; line-height: 1.5; margin: 0; text-align: center;">
                LumiMD helps patients and caregivers stay informed about healthcare visits.
                <br>
                <a href="${portalBaseUrl}/unsubscribe" style="color: #078A94;">Unsubscribe from these emails</a>
              </p>
            </td>
          </tr>
          
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
    `.trim();

        const resend = getResend();
        await resend.emails.send({
            from: 'LumiMD <no-reply@lumimd.app>',
            to: caregiver.email,
            subject: `${patientName} added you as a caregiver on LumiMD`,
            html: emailHtml,
        });

        functions.logger.info('[caregiverEmail] Sent invite email', {
            userId,
            caregiverId: caregiver.id,
            email: caregiver.email,
        });

        return true;

    } catch (error) {
        functions.logger.error('[caregiverEmail] Failed to send invite email', {
            userId,
            caregiverId: caregiver.id,
            error: error instanceof Error ? error.message : 'Unknown error',
        });
        return false;
    }
}

/**
 * Build caregiver visit summary email HTML
 */
function buildCaregiverEmailHtml(data: {
    caregiverName: string;
    patientName: string;
    visitDate: string;
    provider: string;
    summary: string;
    diagnoses: string[];
    medications: { started?: unknown[]; stopped?: unknown[]; changed?: unknown[] };
    nextSteps: string[];
    portalLink: string;
}): string {
    // Build medication changes section
    const medChanges: string[] = [];
    if (data.medications.started && data.medications.started.length > 0) {
        medChanges.push(`<strong>New:</strong> ${formatMedList(data.medications.started)}`);
    }
    if (data.medications.stopped && data.medications.stopped.length > 0) {
        medChanges.push(`<strong>Stopped:</strong> ${formatMedList(data.medications.stopped)}`);
    }
    if (data.medications.changed && data.medications.changed.length > 0) {
        medChanges.push(`<strong>Changed:</strong> ${formatMedList(data.medications.changed)}`);
    }

    const hasMedChanges = medChanges.length > 0;
    const hasNextSteps = data.nextSteps.length > 0;
    const hasDiagnoses = data.diagnoses.length > 0;

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Visit Summary for ${data.patientName}</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #f5f5f5;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; padding: 40px 20px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; background-color: white; border-radius: 12px; overflow: hidden;">
          
          <!-- Header -->
          <tr>
            <td style="background: linear-gradient(135deg, #078A94 0%, #40C9D0 100%); padding: 32px; text-align: center;">
              <h1 style="color: white; margin: 0; font-size: 24px; font-weight: 600;">LumiMD</h1>
              <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0; font-size: 14px;">Visit Summary</p>
            </td>
          </tr>
          
          <!-- Visit Info Bar -->
          <tr>
            <td style="background-color: #F0F9FA; padding: 16px 40px; border-bottom: 1px solid #E2E8F0;">
              <table width="100%">
                <tr>
                  <td style="color: #475569; font-size: 14px;">
                    <strong>${data.patientName}</strong> • ${data.visitDate}
                  </td>
                  <td align="right" style="color: #64748B; font-size: 14px;">
                    ${data.provider}
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          
          <!-- Content -->
          <tr>
            <td style="padding: 40px;">
              <p style="color: #475569; font-size: 16px; line-height: 1.6; margin: 0 0 24px 0;">
                Hi ${data.caregiverName},
              </p>
              
              <p style="color: #475569; font-size: 16px; line-height: 1.6; margin: 0 0 24px 0;">
                ${data.patientName} had a medical visit. Here's a summary:
              </p>
              
              <!-- Summary -->
              ${data.summary ? `
              <div style="background-color: #F8FAFC; border-left: 4px solid #078A94; padding: 16px; margin: 0 0 24px 0; border-radius: 0 8px 8px 0;">
                <p style="color: #1E293B; font-size: 15px; line-height: 1.6; margin: 0;">
                  ${data.summary.substring(0, 500)}${data.summary.length > 500 ? '...' : ''}
                </p>
              </div>
              ` : ''}
              
              ${hasDiagnoses ? `
              <!-- Diagnoses -->
              <h3 style="color: #1E293B; font-size: 16px; font-weight: 600; margin: 24px 0 12px 0;">Discussed Conditions</h3>
              <ul style="color: #475569; font-size: 15px; line-height: 1.6; margin: 0; padding-left: 20px;">
                ${data.diagnoses.map(d => `<li>${d}</li>`).join('')}
              </ul>
              ` : ''}
              
              ${hasMedChanges ? `
              <!-- Medication Changes -->
              <h3 style="color: #1E293B; font-size: 16px; font-weight: 600; margin: 24px 0 12px 0;">Medication Changes</h3>
              <div style="color: #475569; font-size: 15px; line-height: 1.8;">
                ${medChanges.join('<br>')}
              </div>
              ` : ''}
              
              ${hasNextSteps ? `
              <!-- Next Steps -->
              <h3 style="color: #1E293B; font-size: 16px; font-weight: 600; margin: 24px 0 12px 0;">Action Items</h3>
              <ul style="color: #475569; font-size: 15px; line-height: 1.6; margin: 0; padding-left: 20px;">
                ${data.nextSteps.map(s => `<li>${s}</li>`).join('')}
              </ul>
              ` : ''}
              
              <!-- CTA -->
              <div style="text-align: center; margin: 32px 0;">
                <a href="${data.portalLink}" style="display: inline-block; background-color: #078A94; color: white; text-decoration: none; padding: 14px 32px; border-radius: 8px; font-weight: 600; font-size: 16px;">
                  View Full Details
                </a>
              </div>
              
              <p style="color: #94A3B8; font-size: 14px; line-height: 1.5; margin: 24px 0 0 0; text-align: center;">
                A PDF copy is attached to this email.
              </p>
            </td>
          </tr>
          
          <!-- Footer -->
          <tr>
            <td style="background-color: #F8FAFC; padding: 24px 40px; border-top: 1px solid #E2E8F0;">
              <p style="color: #94A3B8; font-size: 12px; line-height: 1.5; margin: 0; text-align: center;">
                You're receiving this because ${data.patientName} added you as a caregiver.
                <br>
                <a href="https://portal.lumimd.app/unsubscribe" style="color: #078A94;">Unsubscribe from these emails</a>
              </p>
            </td>
          </tr>
          
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

/**
 * Format medication list for email
 */
function formatMedList(meds: unknown[]): string {
    return meds.map(med => {
        if (typeof med === 'string') return med;
        if (typeof med === 'object' && med !== null) {
            const m = med as { name?: string; dose?: string };
            return m.dose ? `${m.name} (${m.dose})` : m.name || 'Unknown';
        }
        return 'Unknown';
    }).join(', ');
}
